square/moshi

moshi/src/main/java/com/squareup/moshi/JsonAdapter.java, moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/main/java/com/squareup/moshi/JsonWriter.java, moshi/src/test/java/com/squareup/moshi/ClassJsonAdapterTest.java, moshi/src/test/java/com/squareup/moshi/JsonReaderPathTest.java, moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java, moshi/src/test/java/com/squareup/moshi/MapJsonAdapterTest.java, moshi/src/test/java/com/squareup/moshi/MoshiTest.java, moshi/src/test/java/com/squareup/moshi/TestUtil.java
=> Expose Sink as constructor type.

moshi/src/main/java/com/squareup/moshi/EnumJsonAdapter.java, moshi/src/main/java/com/squareup/moshi/Moshi.java, moshi/src/test/java/com/squareup/moshi/EnumJsonAdapterTest.java
=> EnumJsonAdapter

moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java, moshi/src/main/java/com/squareup/moshi/FromJson.java, moshi/src/main/java/com/squareup/moshi/JsonDataException.java, moshi/src/main/java/com/squareup/moshi/Moshi.java, moshi/src/main/java/com/squareup/moshi/ToJson.java, moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java
This is a fun new API that could make writing JSON adapters
much easier.
=> Adapter methods.

moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java, moshi/src/main/java/com/squareup/moshi/ArrayJsonAdapter.java, moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java, moshi/src/main/java/com/squareup/moshi/CollectionJsonAdapter.java, moshi/src/main/java/com/squareup/moshi/JsonAdapter.java, moshi/src/main/java/com/squareup/moshi/JsonQualifier.java, moshi/src/main/java/com/squareup/moshi/MapJsonAdapter.java, moshi/src/main/java/com/squareup/moshi/Moshi.java, moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java, moshi/src/main/java/com/squareup/moshi/Util.java, moshi/src/test/java/com/squareup/moshi/CircularAdaptersTest.java, moshi/src/test/java/com/squareup/moshi/ClassJsonAdapterTest.java, moshi/src/test/java/com/squareup/moshi/JsonQualifiersTest.java, moshi/src/test/java/com/squareup/moshi/MoshiTest.java
Works like JSR-330's @Qualifier annotation. You may have
multiple qualifiers, or none.
=> New @JsonQualifier annotation.

moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java, moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/main/java/com/squareup/moshi/JsonScope.java, moshi/src/main/java/com/squareup/moshi/JsonWriter.java, moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java, moshi/src/test/java/com/squareup/moshi/JsonWriterPathTest.java
Closes https://github.com/square/moshi/issues/45
=> JsonWriter.getPath().

moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java, moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/main/java/com/squareup/moshi/Moshi.java, moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java, moshi/src/main/java/com/squareup/moshi/Types.java, moshi/src/test/java/com/squareup/moshi/CircularAdaptersTest.java, moshi/src/test/java/com/squareup/moshi/MoshiTest.java, moshi/src/test/java/com/squareup/moshi/ObjectAdapterTest.java
Closes https://github.com/square/moshi/issues/27
=> Runtime type adapter.

moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java, moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java, moshi/src/test/java/com/squareup/moshi/JsonQualifiersTest.java
Closes https://github.com/square/moshi/issues/59
=> Nicer failure messages on partial adapters.

moshi/src/main/java/com/squareup/moshi/Types.java
Not Moshi's responsibility, but pragmatic.
Closes https://github.com/square/moshi/issues/73
=> Make four methods on Types public.

moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java, moshi/src/test/java/com/squareup/moshi/ObjectAdapterTest.java
=> ObjectJsonAdapter should not fail on null values.

examples/src/main/java/com/squareup/moshi/recipes/ReadJsonList.java
Since many people are asking how to parse a json array into a list, I think it's a good idea to have it in recipes.
=> Add read json array recipe

adapters/pom.xml, adapters/src/main/java/com/squareup/moshi/Iso8601Utils.java, adapters/src/main/java/com/squareup/moshi/Rfc3339DateJsonAdapter.java, adapters/src/test/java/com/squareup/moshi/Rfc3339DateJsonAdapterTest.java, pom.xml
Much thanks to Jackson for doing all the real work.
=> RFC3339 adapter.

moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/main/java/com/squareup/moshi/JsonWriter.java
Closes https://github.com/square/moshi/issues/37
=> Audit @link for should-be @linkplain uses.

moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java, moshi/src/main/java/com/squareup/moshi/CollectionJsonAdapter.java, moshi/src/main/java/com/squareup/moshi/LinkedHashTreeMap.java, moshi/src/main/java/com/squareup/moshi/Moshi.java, moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java, moshi/src/main/java/com/squareup/moshi/Types.java
Remove 13 synthetic methods to 601 from 614.
=> Remove creation of synthetic accessor methods.

moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java, moshi/src/test/java/com/squareup/moshi/MoshiTest.java
Attempt to fix #115. Inspired by Gson's implementation. No regex support at this point though.
=> Enable Json annotation for enum values.

moshi/src/test/java/com/squareup/moshi/PromoteNameToValueTest.java
See also https://github.com/google/gson/pull/809/files
=> Confirm Moshi can handle unquoted numeric keys.

moshi/src/main/java/com/squareup/moshi/BufferedSourceJsonReader.java, moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
Prefer LinkedHashMap for maps that will be queried heavily.
Inline a single-line method to refill the buffer.
=> Small optimizations to JSON parsing.

moshi/src/main/java/com/squareup/moshi/ClassFactory.java
Fixed https://github.com/square/moshi/issues/117
=> Added support for pre-Gingerbread.

moshi/src/main/java/com/squareup/moshi/BufferedSourceJsonReader.java, moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java, moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java, moshi/src/test/java/com/squareup/moshi/BufferedSourceJsonReaderTest.java
Also rename our own Selection class to Options since it's semantically
the same thing.
https://github.com/square/okio/pull/215
=> Track Okio snapshot API change to Options.

moshi/src/main/java/com/squareup/moshi/Types.java
it added Override annotation on ParameterizedTypeImpl, WildcardTypeImpl and GenericArrayTypeImpl.
=> Add Override annotation

moshi/src/main/java/com/squareup/moshi/BufferedSourceJsonReader.java, moshi/src/test/java/com/squareup/moshi/BufferedSourceJsonReaderTest.java
Related to https://github.com/google/gson/issues/824
=> Fail on invalid escapes.

moshi/src/main/java/com/squareup/moshi/BufferedSourceJsonReader.java
Closes: https://github.com/square/moshi/issues/122
=> Don't link to Google's internal bugtracker.

moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java, moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java
Closes: https://github.com/square/moshi/issues/142
=> Permit JsonAdapters to be injected in toJson(), fromJson() methods.

CHANGELOG.md
It's actualy `JsonAdapter`'s not  `JsonReader`s
=> Fix small changelog nit.

moshi/src/main/java/com/squareup/moshi/BufferedSourceJsonReader.java, moshi/src/test/java/com/squareup/moshi/BufferedSourceJsonReaderTest.java
Closes: https://github.com/square/moshi/issues/209
=> Don't reject escaped forward slashes.

moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java, moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java
https://gist.github.com/SteinerOk/82f90fb570ef9ad35e2833ee96747939
=> Adapter methods get nulls if they accept JsonReader/JsonWriter.

moshi/src/main/java/com/squareup/moshi/ArrayJsonAdapter.java
It's not a bug. But really helps during debugging.
=> Make ArrayJsonAdapter implement toString().

moshi/src/main/java/com/squareup/moshi/ObjectJsonReader.java, moshi/src/test/java/com/squareup/moshi/JsonReaderPathTest.java, moshi/src/test/java/com/squareup/moshi/ObjectJsonReaderTest.java
https://github.com/square/moshi/issues/89
=> First step of a JsonReader that reads a DOM.

moshi/src/main/java/com/squareup/moshi/ObjectJsonReader.java, moshi/src/test/java/com/squareup/moshi/BufferedSourceJsonReaderTest.java, moshi/src/test/java/com/squareup/moshi/JsonReaderFactory.java, moshi/src/test/java/com/squareup/moshi/JsonReaderPathTest.java, moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java, moshi/src/test/java/com/squareup/moshi/ObjectJsonReaderTest.java, moshi/src/test/java/com/squareup/moshi/TestUtil.java
https://github.com/square/moshi/issues/89
=> Fix some bugs and increase tests for ObjectJsonReader.

moshi/src/main/java/com/squareup/moshi/BufferedSourceJsonReader.java, moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/main/java/com/squareup/moshi/ObjectJsonReader.java, moshi/src/test/java/com/squareup/moshi/BufferedSourceJsonReaderTest.java, moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java
This is just to make the discusion on #165 rolling.
=> Make JsonReader.selectName and JsonReader.selectString public.

moshi/src/main/java/com/squareup/moshi/BufferedSourceJsonReader.java
This will save us one loop. Not sure how to test this tho, or even if we need to.
=> Avoid calling source.select() if the value is buffered.

moshi/src/main/java/com/squareup/moshi/JsonAdapter.java, moshi/src/test/java/com/squareup/moshi/MoshiTest.java
https://github.com/square/moshi/issues/89
=> New APIs: JsonAdapter.toJsonObject, fromJsonObject.

moshi/src/main/java/com/squareup/moshi/BufferedSinkJsonWriter.java, moshi/src/main/java/com/squareup/moshi/BufferedSourceJsonReader.java, moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/main/java/com/squareup/moshi/JsonWriter.java, moshi/src/main/java/com/squareup/moshi/ObjectJsonReader.java, moshi/src/main/java/com/squareup/moshi/ObjectJsonWriter.java, moshi/src/test/java/com/squareup/moshi/JsonWriterPathTest.java
It turns out that we can reuse a lot of code with inheritance. Who knew?
=> Promote stack management to the JsonReader/JsonWriter supertypes.

moshi/src/main/java/com/squareup/moshi/Moshi.java, moshi/src/main/java/com/squareup/moshi/Types.java, moshi/src/test/java/com/squareup/moshi/TypesTest.java
From https://github.com/square/moshi/pull/236.
I don't know what this method should be called yet.
This is way too easy, so I am misunderstanding something. Can I get a nudge in the right direction?
=> Add Types.createJsonQualifierImplementation

examples/src/main/java/com/squareup/moshi/recipes/Unwrap.java
Here's a swing to help https://github.com/square/moshi/issues/136
I won't take offense if you have different examples in mind or just don't like these, obviously, haha!
=> Add Unwrap JsonAdapter.Factory sample

moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java, moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java
Moves `readJsonValue` up to `JsonReader`.
Just want to start the discussion.
The docs need improvement.
Is a `JsonWriter.writeJsonValue(Object value)` useful?
Also, I think I should move `defaultIfDataException` to a different change, if this is something that you'd like to add at all.
=> Add JsonReader.readJsonValue

README.md
Oops, I missed this yesterday.
=> Fix README version number

moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java, moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java
Lemme know if you have a better wording for the message.
=> Update adapter methods ISE message.

moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java, moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java
Closes #271.
Are there any more test cases I might not be thinking of?
=> Allow easy delegates in adapter methods.

moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java
Obsoletes https://github.com/square/moshi/pull/129/files
=> Add a test to confirm types are canonicalized.

kotlin/src/main/java/com/squareup/moshi/KotlinJsonAdapter.kt, kotlin/src/test/java/com/squareup/moshi/KotlinJsonAdapterTest.kt
Closes: https://github.com/square/moshi/issues/284
=> KotlinJsonAdapter shouldn't convert enums.

README.md
It's the little things...
https://en.wiktionary.org/wiki/voil%C3%A0
=> FIX TYPO: Voila -> Voilà

README.md
updated proguard configuration for custom Json Adapters @FromJson/@ToJson cases
=> proguard config updates

adapters/README.md
Title says it all! Took the format from https://github.com/square/retrofit explanation of converters
=> Document `moshi-adapters` artifact

adapters/README.md
Updated the example with the correct API https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/Moshi.java#L155
=> Fix builder calls to new API

moshi/src/main/java/com/squareup/moshi/Types.java
Nobody uses this helper method.
=> Remove Types.equal.

moshi/src/main/java/com/squareup/moshi/JsonAdapter.java, moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/main/java/com/squareup/moshi/JsonWriter.java, moshi/src/main/java/com/squareup/moshi/Moshi.java, moshi/src/main/java/com/squareup/moshi/Types.java
Moshi's a good small library to try this out on.
If this looks good, we could file issues on other libraries to get these in.  If this doesn't look good, no time was lost.
=> Add @CheckReturnValue to appropriate public APIs.

moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/main/java/com/squareup/moshi/JsonUtf8Writer.java, moshi/src/main/java/com/squareup/moshi/JsonValueWriter.java, moshi/src/main/java/com/squareup/moshi/JsonWriter.java, moshi/src/test/java/com/squareup/moshi/JsonUtf8ReaderTest.java, moshi/src/test/java/com/squareup/moshi/JsonWriterTest.java, moshi/src/test/java/com/squareup/moshi/MoshiTest.java, moshi/src/test/java/com/squareup/moshi/TestUtil.java
Closes https://github.com/square/moshi/issues/348
=> Support up to 255 levels of nesting.

moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java, moshi/src/test/java/com/squareup/moshi/MoshiTest.java
=> Don't handle WildcardTypes in ClassJsonAdapter.

moshi/src/main/java/com/squareup/moshi/JsonValueReader.java, moshi/src/test/java/com/squareup/moshi/JsonUtf8ReaderTest.java, moshi/src/test/java/com/squareup/moshi/JsonValueReaderTest.java, moshi/src/test/java/com/squareup/moshi/JsonWriterTest.java, moshi/src/test/java/com/squareup/moshi/TestUtil.java
Follow up to https://github.com/square/moshi/pull/349
=> Fix JsonValueReader to support up to 255 levels of nesting.

examples/src/main/java/com/squareup/moshi/recipes/CustomAdapterFactory.java
Closes: https://github.com/square/moshi/issues/136
=> Add a standard example for JSON adapter factories.

examples/src/main/java/com/squareup/moshi/recipes/ByteStrings.java
Closes: https://github.com/square/moshi/issues/31
=> ByteStrings example.

adapters/src/main/java/com/squareup/moshi/Iso8601Utils.java
This file was removed from master a few months ago.
=> Add permalink to ISO8601Utils.java.

moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java, moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java
void toJson(JsonWriter, JsonAdapter) does not make sense. This looks like my copy-paste error.
=> Fix error message for invalid toJson signature.

moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
I linked someone to this code today and noticed that is seemed arbitrarily complex with regard to branching and locals, probably as a result of refactoring.
=> Reduce visual complexity of branching.

moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java, moshi/src/test/java/com/squareup/moshi/ClassJsonAdapterTest.java
I broke this in https://github.com/square/moshi/pull/406
=> Fix ClassJsonAdapter to handle ParameterizedTypes.

moshi/src/main/java/com/squareup/moshi/JsonAdapter.java, moshi/src/test/java/com/squareup/moshi/JsonAdapterTest.java
I hope this doesn't surprise anybody with existing broken adapters.
=> JsonAdapter.fromJson(String) must fully consume.

kotlin-codegen/compiler/pom.xml, kotlin-codegen/compiler/src/main/java/com/squareup/moshi/AdapterGenerator.kt, kotlin-codegen/compiler/src/test/java/com/squareup/moshi/CompilerTest.kt, kotlin-codegen/compiler/src/test/java/com/squareup/moshi/KotlinCompilerCall.kt, kotlin-codegen/compiler/src/test/java/com/squareup/moshi/KotlinCompilerResult.kt, pom.xml
=> Call the kotlin compiler from within a test case.

kotlin/src/main/java/com/squareup/moshi/kotlin/KotlinJsonAdapter.kt, moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java, moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java, moshi/src/main/java/com/squareup/moshi/Moshi.java, moshi/src/main/java/com/squareup/moshi/Types.java, moshi/src/main/java/com/squareup/moshi/internal/Util.java, moshi/src/test/java/com/squareup/moshi/TypesTest.java
unfortunately requires moving most of the internal type utilities into the Util. couldn't think of anything clever to make the diff not a mess.
=> Hide Types.resolve.

examples/src/main/java/com/squareup/moshi/recipes/FallbackEnum.java
This was copied code from a different example that used the delegate annotations.
=> Simplify example code.

kotlin-codegen/compiler/src/main/java/com/squareup/moshi/AdapterGenerator.kt, kotlin-codegen/compiler/src/main/java/com/squareup/moshi/DelegateKey.kt, kotlin-codegen/compiler/src/main/java/com/squareup/moshi/JsonClassCodeGenProcessor.kt, kotlin-codegen/compiler/src/main/java/com/squareup/moshi/PropertyGenerator.kt, kotlin-codegen/compiler/src/main/java/com/squareup/moshi/TargetConstructor.kt, kotlin-codegen/compiler/src/main/java/com/squareup/moshi/TargetParameter.kt, kotlin-codegen/compiler/src/main/java/com/squareup/moshi/TargetProperty.kt, kotlin-codegen/compiler/src/main/java/com/squareup/moshi/TargetType.kt, kotlin-codegen/compiler/src/test/java/com/squareup/moshi/CompilerTest.kt, kotlin-codegen/compiler/src/test/java/com/squareup/moshi/KotlinCompilerCall.kt
This is intended to make it easier to implement support for subtypes.
=> Model target types, parameters, constructors and properties

kotlin/src/main/java/com/squareup/moshi/kotlin/KotlinJsonAdapter.kt, moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java, moshi/src/main/java/com/squareup/moshi/JsonAdapter.java, moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.java, moshi/src/main/java/com/squareup/moshi/JsonValueReader.java, moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java, moshi/src/test/java/com/squareup/moshi/JsonUtf8ReaderTest.java, moshi/src/test/java/com/squareup/moshi/MoshiTest.java
=> Add JsonReader.skipName.

kotlin/src/main/java/com/squareup/moshi/kotlin/KotlinJsonAdapter.kt, kotlin/src/test/java/com/squareup/moshi/kotlin/KotlinJsonAdapterTest.kt
=> Fix path for non-null value message.

kotlin/src/test/java/com/squareup/moshi/kotlin/KotlinJsonAdapterTest.kt
The message got improved in a conflicting change to these tests being added.
=> Fix some tests that have the wrong expected exception message

moshi/src/main/java/com/squareup/moshi/JsonUtf8Writer.java, moshi/src/main/java/com/squareup/moshi/JsonValueWriter.java, moshi/src/main/java/com/squareup/moshi/JsonWriter.java, moshi/src/test/java/com/squareup/moshi/JsonUtf8WriterTest.java, moshi/src/test/java/com/squareup/moshi/JsonValueWriterTest.java, moshi/src/test/java/com/squareup/moshi/PromoteNameToValueTest.java
=> Allow writing out raw JSON.

README.md
=> Fix adapter factory name in proguard mention

moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/test/java/com/squareup/moshi/JsonReaderPathTest.java, moshi/src/test/java/com/squareup/moshi/JsonUtf8ReaderTest.java
This encourages skipName over nextName.
=> Add more CheckReturnValues for JsonReader.

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/AdapterGenerator.kt
Before this was just adding both as varargs of "value"
=> Fix GeneratedAnnotation member definition

moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.java, moshi/src/main/java/com/squareup/moshi/JsonValueReader.java, moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java
I doubt anybody is relying on the previous behavior.
=> Fix hasNext to return false at document end.

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/AdapterGenerator.kt, kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/TargetProperty.kt, kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt
=> Fix dollar sign escaping for json key names.

adapters/src/main/java/com/squareup/moshi/adapters/EnumJsonAdapter.java, adapters/src/test/java/com/squareup/moshi/adapters/EnumJsonAdapterTest.java
for consideration. dunno what to call this type.
=> Add EnumJsonAdapter to adapters module.

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/TypeRenderer.kt, kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt
Otherwise we crash with an exception attempting to create an adapter
for an enclosed type that has a type parameter.
I ran into this looking for a test case for issue 615.
https://github.com/square/moshi/issues/615
=> Call Types.newParameterizedTypeWithOwner when necessary.

kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt
Closes: https://github.com/square/moshi/issues/662
=> Don't do Kotlin reflection on a non-Kotlin class.

moshi/src/test/java/com/squareup/moshi/JsonQualifiersTest.java
Their seems to have been concurrency between #616 and #659
=> Fix JsonQualifiers test

adapters/src/main/java/com/squareup/moshi/adapters/RuntimeJsonAdapterFactory.java, adapters/src/test/java/com/squareup/moshi/adapters/RuntimeJsonAdapterFactoryTest.java
=> Fix RuntimeJsonAdapterFactory breaking with Object as the base type.

moshi/src/main/resources/META-INF/proguard/moshi.pro
=> Proguard config: keep field names of annotated enums

moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.java, moshi/src/main/java/com/squareup/moshi/JsonValueReader.java, moshi/src/test/java/com/squareup/moshi/JsonCodecFactory.java, moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java
Related to https://github.com/square/moshi/issues/672
=> Implement peekJson() for JsonValueReader

adapters/src/main/java/com/squareup/moshi/adapters/RuntimeJsonAdapterFactory.java, adapters/src/test/java/com/squareup/moshi/adapters/RuntimeJsonAdapterFactoryTest.java
This is a bit awkward because JsonReader.Options doesn't tell you
what its values are.
Also awkward because we don't yet have an equivalent to stream
the encode of the value.
=> Change RuntimeJsonAdapterFactory to peek for type names.

adapters/src/main/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactory.java, adapters/src/test/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactoryTest.java
Also expand the documentation.
=> Rename RuntimeJsonAdapterFactory to PolymorphicJsonAdapterFactory

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/AdapterGenerator.kt
=> Do not check required property for null second time

moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
Followup from https://github.com/square/moshi/pull/749#discussion_r235224202
=> Use faster isAnnotationPresent check

kotlin/codegen/pom.xml
=> Remove shading of KotlinPoet

pom.xml
Closes #777
Note that this doesn't cover any Kotlin 1.3 language features. I think the only one we'd be interested in is inline classes and unsigned types, but they're still experimental
=> Update to Kotlin 1.3.21

kotlin/codegen/pom.xml, kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/AdapterGenerator.kt, kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessor.kt, kotlin/tests/pom.xml, pom.xml
This adds support for incremental compilation in gradle via incap helper and marking the code gen as `ISOLATING`.
Resolves #589
=> Support gradle incremental processing in code gen

kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt
Followup fixes from the previous PR
=> Fast followups from #899

moshi/src/main/java/com/squareup/moshi/ClassFactory.java
Resolves #872. Not sure if we want to try caching some of these lookups
=> Don't try to access unsafe APIs on android 29+

kotlin/codegen/pom.xml, pom.xml
Resolves #935 
Having the separate tests artifact is a nice little built-in integration test for this
=> Shade kotlinpoet-metadata and kotlinx-metadata

kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt, kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest_CustomGeneratedClassJsonAdapter.kt, kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/LooksLikeAClass/ClassInPackageThatLooksLikeAClass.kt
=> Fix misspelled codgen package in tests

moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.java, moshi/src/main/java/com/squareup/moshi/JsonValueReader.java, moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java, moshi/src/test/java/com/squareup/moshi/MoshiTest.java
=> Point at the offending name when failing on unknown

pom.xml
https://github.com/tschuchortdev/kotlin-compile-testing/releases/tag/1.2.3
* Check file extensions automatically when creating `SourceFile`s with the new factory functions
* Less noisy output/verbose flag actually works as intended
=> Update kotlin-compile-testing to 1.2.3

kotlin/codegen/pom.xml, kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt, pom.xml
This updates to KotlinPoet 1.4.1 and Kotlin 1.3.50
This fixes #955 and adds a regression test
=> Update to KotlinPoet 1.4.1/Kotlin 1.3.50

moshi/src/main/java/com/squareup/moshi/ClassFactory.java
The attempted fix replaced a warning with a crash. I believe that a
warning is a better developer experience than a crash.
This reverts commit c0639316b108ea4ba98d7c74187de4078858c660.
=> Go back to using Unsafe APIs to create instances without constructors.

kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt, kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt, kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
=> Support multiple transient properties in KotlinJsonAdapter.

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt, kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/MultipleMasksTest.kt
Resolves #977 using the methodology roughly described here: https://github.com/square/moshi/issues/977#issuecomment-547691422
=> Support 32+ parameter constructors in code gen

pom.xml
=> KotlinPoet 1.4.3

kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
=> Add an abstract non-unit function regression for #974

pom.xml
This fixes support for reified inline types.
Fixes #1008
=> Upgrade to KotlinPoet 1.4.4

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/TypeRenderer.kt, kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt, kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
=> Strip type annotations from TypeRenderer and asTypeBlock()

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt, kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
=> Don't linebreak keys with spaces

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt, kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt, kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
This depends on https://github.com/square/kotlinpoet/pull/865 being released
=> Improve the way Json.name is fetched for codegen

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt, kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt, moshi/src/main/java/com/squareup/moshi/internal/Util.java
=> Check types parameter size in init

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/ProguardRules.kt, kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessorTest.kt
Signed,
Person that always forgets how to do modulo counting
Manually verified and checked the counts this time to be triple sure
=> Fix mask count in proguard rule gen

README.md
=> Tweak README nullSafe() example

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt, kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/ProguardRules.kt, kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessorTest.kt
Proguard wants to speak reflection names
=> Fix reflection names in generated proguard files

moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/main/java/com/squareup/moshi/JsonWriter.java, moshi/src/test/java/com/squareup/moshi/JsonWriterTest.java
This is symmetric with JsonReader.readJsonValue in that it writes an Object comprised of maps, lists, and some scalars.
=> Add JsonWriter.jsonValue API

moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java, moshi/src/test/java/com/squareup/moshi/MoshiTest.java
A new user of Moshi might try to make a class like
data class Response (
val users: ArrayList<User>
)
Then when trying to create a JsonAdapter for it, they get an unhelpful error
message like
Platform class java.util.ArrayList in java.util.ArrayList<com.example.User>
requires explicit JsonAdapter to be registered
which doesn't explain what they should do to fix the problem. In fact what it
hints towards is that the user should implement a JsonAdapter for ArrayList,
when really they just need to change the type to List!
Now the error looks like
No JsonAdapter for java.util.ArrayList<com.example.User>, you should use
List instead of ArrayList (Moshi only supports the collection interfaces
by default).
=> Improve error when incorrectly trying to use a collection class like ArrayList instead of List

kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt
https://github.com/square/moshi/issues/803
=> R8 triggers VerifyError on KitKat devices

README.md
=> Update README notes about R8/proguard

moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java
=> Expose getStrings() option on JsonReader.Options

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/ProguardRules.kt
appendLn is deprecated in kotlin 1.4
=> Switch to new appendLine APIs

buildSrc/src/main/kotlin/Dependencies.kt
Just a bunch of small bugfixes
=> Update to Kotlin 1.4.10

moshi/src/main/java/com/squareup/moshi/JsonReader.java, moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.java, moshi/src/main/java/com/squareup/moshi/JsonValueReader.java, moshi/src/main/java/com/squareup/moshi/JsonValueSource.java, moshi/src/test/java/com/squareup/moshi/FlattenTest.java, moshi/src/test/java/com/squareup/moshi/JsonCodecFactory.java, moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java, moshi/src/test/java/com/squareup/moshi/JsonUtf8ReaderTest.java
The streaming side of https://github.com/square/moshi/issues/675
We can still add a nicer wrapper on top to read the JSON value as
a string.
=> New public API, JsonReader.nextSource()

README.md, examples/src/main/java/com/squareup/moshi/recipes/IncludeNullsForAnnotatedTypes.java, examples/src/main/java/com/squareup/moshi/recipes/IncludeNullsForOneType.java, moshi/src/main/java/com/squareup/moshi/Moshi.java, moshi/src/test/java/com/squareup/moshi/MoshiTest.java
This is mostly useful for KotlinJsonAdapterFactory.
=> Moshi.Builder.addLast()

.gitignore, build.gradle.kts, examples/src/main/java/com/squareup/moshi/recipes/IncludeNullsForAnnotatedTypes.java, examples/src/main/java/com/squareup/moshi/recipes/IncludeNullsForOneType.java
This updates to Dokka 1.4.10 and prepares for a future with Kotlin rewrite and mkdocs
=> Prepare dokka

gradle.properties
See https://github.com/Kotlin/dokka/issues/1405
Currently are failing https://github.com/square/moshi/runs/1171362091
=> Fix snapshots by upping metaspace size

.github/workflows/build.yml
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target
=> Use pull_request_target

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt
These are unlikely to actually go away in 2.0 since they make sense in this case
=> Suppress some poet deprecations

moshi/src/main/java/com/squareup/moshi/JsonAdapter.java
=> Add some short basic docs to JsonAdapter methods

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt
One example I found for this is when a property is annotated with android's `@SuppressLint`, which is only available from the android jar and not visible during apt. This should just be a warning (if even?) and not a hard error.
=> Warn on missing TypeElement rather than error

adapters/japicmp/build.gradle.kts, build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, moshi/japicmp/build.gradle.kts
~kotlinx-metadata 0.2.0~ Handled in another PR
kotlin 1.4.31
spotless 5.11.0
animalsniffer 1.5.3
japicmp 0.2.9
junit 4.13.2
kotlinpoet 1.8.0
=> Update more dependencies

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
Resolves #1302
Ported from my KSP impl [KSP impl](https://github.com/ZacSweers/MoshiX/pull/86). Now this class would result in in the associated generated adapter:
```kotlin
@JsonClass(generateAdapter = true)
data class Example(val param1: String, val param2: String = "")
```
```kotlin
public class ExampleJsonAdapter(
moshi: Moshi
) : JsonAdapter<Example>() {
// Properties...
public override fun toString(): String = buildString(29) {
append("GeneratedJsonAdapter(").append("Example").append(')') }
public override fun fromJson(reader: JsonReader): Example {
var param1: String? = null
var param2: String? = null
var mask0 = -1
reader.beginObject()
while (reader.hasNext()) {
when (reader.selectName(options)) {
0 -> param1 = stringAdapter.fromJson(reader) ?: throw Util.unexpectedNull("param1", …
```
=> Invoke constructor directly if all params with default are set

moshi/src/main/java/com/squareup/moshi/JsonReader.java
=> JsonReader.nextSource javadoc

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/apt/AppliedType.kt, kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/apt/JsonClassCodegenProcessor.kt, kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/apt/MoshiCachedClassInspector.kt, kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/apt/metadata.kt, kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/JavaSuperclass.java, kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/apt/JsonClassCodegenProcessorTest.kt
In preparation for introducing a ksp subpackage later
=> Move apt-specific classes to apt package

README.md
* My pull request has a descriptive title.
* It targets the master branch.
* All files I've changed are in the same language i.e. English.
=> fix: corrected a grammatical error.

gradle/libs.versions.toml, kotlin/codegen/build.gradle.kts, kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/apt/JsonClassCodegenProcessor.kt, kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/apt/MoshiCachedClassInspector.kt, kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/apt/metadata.kt
Unifies the kotlin-metadata artifacts into one
=> Update KotlinPoet to 1.10.0

README.md
Added Kotlin Examples, as discussed in Issue #1345
=> Update README.md to include Kotlin Examples

gradle/wrapper/gradle-wrapper.properties
https://docs.gradle.org/7.3/release-notes.html
Highlights include
- Java 17
- Tasks can mark themselves as untracked
=> Update to Gradle 7.3

kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/shadedUtil.kt
I believe that's this:
https://github.com/google/ksp/blob/main/api/src/main/kotlin/com/google/devtools/ksp/utils.kt
=> Attribute copyright to the actual owner

moshi/records-tests/src/test/java/com/squareup/moshi/records/RecordsTest.java, moshi/src/main/java16/com/squareup/moshi/RecordJsonAdapter.java
=> Remove redundant static modifiers on records

moshi/build.gradle.kts, moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.kt
This accidentally snuck into master because it predates the Kotlin 1.6 upgrade
=> Fix exhaustive when in JsonUtf8Reader

README.md
Corrected the latest version in `Maven` sample. Synced the version in maven and gradle samples.
=> Corrected the latest version in Maven sample in README file

moshi-adapters/src/main/java/com/squareup/moshi/Rfc3339DateJsonAdapter.kt, moshi-adapters/src/main/java/com/squareup/moshi/adapters/EnumJsonAdapter.kt, moshi-adapters/src/main/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactory.kt, moshi-adapters/src/main/java/com/squareup/moshi/adapters/Rfc3339DateJsonAdapter.kt, moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.kt
=> Use Okio IOException in Kotlin classes

moshi-kotlin-codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
=> Don't suffix the value param when overriding

moshi-kotlin-codegen/build.gradle.kts, moshi/build.gradle.kts
=> Remove redundant opt-in flags

.github/workflows/build.yml, build.gradle.kts, gradle/libs.versions.toml, moshi-kotlin-codegen/src/test/java/com/squareup/moshi/kotlin/codegen/apt/JsonClassCodegenProcessorTest.kt, moshi-kotlin-codegen/src/test/java/com/squareup/moshi/kotlin/codegen/ksp/JsonClassSymbolProcessorTest.kt
Also includes a JDK 20 upgrade, KSP updates, and KCT updates
=> Update to Kotlin 1.9.0

README.md
https://github.com/square/moshi/discussions/1789
I have updated the dependency section in the README.md to reflect the latest version.
=> Update README.md dependency version 1.14.0 to 1.15.0

moshi-adapters/src/main/java/com/squareup/moshi/adapters/EnumJsonAdapter.kt
It is not guaranteed to be used at this point and performs a decent amount of allocation and computation.
=> Do not allocate path outside conditionals

gradle/libs.versions.toml, moshi-kotlin-codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/MoshiApiUtil.kt, moshi-kotlin-codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/TargetTypes.kt, moshi-kotlin-codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/shadedUtil.kt, moshi-kotlin-tests/build.gradle.kts, moshi-kotlin-tests/codegen-only/build.gradle.kts, moshi-kotlin-tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt, moshi/build.gradle.kts, moshi/gradle.properties
=> Kotlin 2.1 and friends

moshi-kotlin-codegen/src/test/java/com/squareup/moshi/kotlin/codegen/ksp/JsonClassSymbolProcessorTest.kt
Preparing a KSP2 branch to merge when that's ready
=> Remove KSP1 support in tests

moshi-kotlin-codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/KspUtil.kt
This is never hit in KSP2 anymore. Ref: https://github.com/square/moshi/pull/2000#discussion_r2395831139
=> Remove KSName handling from KspUtil

CHANGELOG.md, moshi/src/main/java/com/squareup/moshi/internal/Util.kt
=> Refuse j$ APIs as platform types

moshi-kotlin/build.gradle.kts
This isn't necessary and leftover
Resolves #2012
=> Fix dokka in moshi-kotlin

build.gradle.kts
dokka's API is... not always obvious
=> Fix okio package list

moshi-adapters/build.gradle.kts, moshi/build.gradle.kts
For some reason I missed these
=> Remove remaining leftover dokka configs
