- moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java
- moshi/src/main/java/com/squareup/moshi/Util.java
- moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java
When the annotation is present, the adapter method is used. When
it isn't, it isn't.
> Support @Nullable in Adapter Methods.

- moshi/src/main/java/com/squareup/moshi/JsonDataException.java
- moshi/src/main/java/com/squareup/moshi/JsonReader.java
- moshi/src/main/java/com/squareup/moshi/JsonWriter.java
- moshi/src/main/java/com/squareup/moshi/MapJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java
- moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java
- moshi/src/test/java/com/squareup/moshi/MapJsonAdapterTest.java
- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
We throw IllegalStateException when the application code is
internally inconsistent, such as when it closes and then writes
or similar.
We throw an IOException when the source JSON is structurally
invalid, such as when strings are unquoted in strict mode.
And we throw JsonDataException when the application code is
correct, and the JSON is well-formed, but the application code
and JSON disagree with one another.
> Throw JsonDataException consistently.

- moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java
- moshi/src/main/java/com/squareup/moshi/ClassFactory.java
- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/CollectionJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/JsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/MapJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/Moshi.java
- moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java
- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
This adds a toString() to most adapters. The format isn't perfect, but
it should make step-debugging easier.
Define the precedence order of adapter factories.
Forbid registering adapters with annotation literals if those annotations
need values to be provided.
> Adapter caching, plus other ergonomic features.

- moshi/src/main/java/com/squareup/moshi/JsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/JsonReader.java
- moshi/src/main/java/com/squareup/moshi/JsonWriter.java
- moshi/src/test/java/com/squareup/moshi/ClassJsonAdapterTest.java
- moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java
- moshi/src/test/java/com/squareup/moshi/JsonWriterPathTest.java
- moshi/src/test/java/com/squareup/moshi/JsonWriterTest.java
- moshi/src/test/java/com/squareup/moshi/MapJsonAdapterTest.java
- moshi/src/test/java/com/squareup/moshi/PromoteNameToValueTest.java
- moshi/src/test/java/com/squareup/moshi/TestUtil.java
This opens the door to later implementations of these types that write
to something other than a stream. In particular, we could have a
JsonReader that reads from a DOM-like object, or a JsonWriter that
creates such an object.
> JsonReader.of() and JsonWriter.of() instead of constructors.

- moshi/src/main/java/com/squareup/moshi/Types.java
To facilitate custom JsonAdapter.Factory implementations.
When I closed #84 I was fooled by my Android Studio which was using a cached version of moshi, or something.
Like @JakeWharton said in that issue `getRawType` and `collectionElementType` were indeed non-public before.
This commit makes them public.
> Make two methods on Types public.

- moshi/src/main/java/com/squareup/moshi/JsonWriter.java
Is the default value of `JsonWriter.serializeNulls` `false`?
> Doc fix for JsonWriter.serializeNulls

- moshi/src/main/java/com/squareup/moshi/Moshi.java
- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
Added `Moshi#newBuilder` method, which creates a `Moshi.Builder` with all custom factories.
Discused in #101
> Possibility to create new `Moshi.Builder` from `Moshi` instance.

- moshi/src/main/java/com/squareup/moshi/Moshi.java
Avoids unnecessary work spent in growing the list.
> Presize Lists

- moshi/src/main/java/com/squareup/moshi/BufferedSinkJsonWriter.java
- moshi/src/main/java/com/squareup/moshi/BufferedSourceJsonReader.java
- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/JsonReader.java
- moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java
- moshi/src/test/java/com/squareup/moshi/BufferedSourceJsonReaderTest.java
- pom.xml
This isn't yet public API.
This relies on an unreleased Okio API.
This has a significant impact on performance. I measured parsing performance
improve from 89k ops/sec to 140k ops/sec on one benchmark.
> Optimize reading one of several expected values with Selection

- moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java
- moshi/src/main/java/com/squareup/moshi/Moshi.java
- moshi/src/main/java/com/squareup/moshi/Types.java
- moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java
Unfortunately we shouldn't be relying on equals() and hashCode() of the
default implementations anywhere.
> Be more aggressive about canonicalizing types.

- moshi/src/main/java/com/squareup/moshi/BufferedSinkJsonWriter.java
- moshi/src/main/java/com/squareup/moshi/JsonWriter.java
- moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java
- moshi/src/test/java/com/squareup/moshi/BufferedSinkJsonWriterTest.java
Autoboxing resolves boxed longs and doubles to `value(Number)`, but a boxed boolean would otherwise resolve to `value(boolean)` with an implicit call to `booleanValue()` which has the potential to throw NPEs.
Same change as https://github.com/google/gson/pull/836
> Add writer value overload for boxed booleans.

- pom.xml
This will give downstream consumers of the next release a version of Okio with `rangeEquals` for BOM skipping (like Retrofit).
> Point at the latest Okio.

- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
It's unlikely that these will be stable, or that they'll do anything reasonable.
Closes: https://github.com/square/moshi/issues/185
> Omit Kotlin and Scala platform types from the class adapter.

- moshi/src/main/java/com/squareup/moshi/Types.java
- moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java
- moshi/src/test/java/com/squareup/moshi/TypesTest.java
This was broken becase reflection was providing owner types but our
API didn't have a way to specify them.
Closes: https://github.com/square/moshi/issues/148
> Fix enclosed types with adapter methods.

- moshi/src/main/java/com/squareup/moshi/BufferedSinkJsonWriter.java
- moshi/src/main/java/com/squareup/moshi/BufferedSourceJsonReader.java
- moshi/src/main/java/com/squareup/moshi/JsonDataException.java
- moshi/src/main/java/com/squareup/moshi/MapJsonAdapter.java
- moshi/src/test/java/com/squareup/moshi/BufferedSinkJsonWriterTest.java
- moshi/src/test/java/com/squareup/moshi/BufferedSourceJsonReaderTest.java
- moshi/src/test/java/com/squareup/moshi/MapJsonAdapterTest.java
- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
With the implicit enclosing document this is 32 levels total. The limit
is arbitrary but sufficient - deeper limits yield code that fails with
StackOverflowExceptions during the depth-first traversal.
We were previously broken in JsonWriter on this - the code we added to
support path building was accessing the top of the stack before the
stack had been resized, causing a crash. Because this crash has existed
forever without much outcry we know the limit is likely sufficient for
our existing users.
Closes: https://github.com/square/moshi/issues/189
> Limit to 31 levels of nested structure.

- moshi/src/main/java/com/squareup/moshi/Moshi.java
- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
I don't know if that test is really necessary.
I used `IllegalArgumentException` (not `NullPointerException`) for consistency with the existing usage.
> Disallow Moshi.Builder.add(null)

- moshi/src/test/java/com/squareup/moshi/JsonReaderFactory.java
This will save some seconds when trying to realise which parameterized tests are failing.
> Make JsonReaderFactory implement toString().

- moshi/src/main/java/com/squareup/moshi/BufferedSinkJsonWriter.java
- moshi/src/main/java/com/squareup/moshi/JsonWriter.java
- moshi/src/main/java/com/squareup/moshi/MapJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/ObjectJsonReader.java
- moshi/src/main/java/com/squareup/moshi/ObjectJsonWriter.java
- moshi/src/test/java/com/squareup/moshi/MapJsonAdapterTest.java
- moshi/src/test/java/com/squareup/moshi/PromoteNameToValueTest.java
This was renamed from promoteNameToValue(). Also run the test on both types of
codecs and fix some implementation issues that uncovered.
> Implement promoteValueToName() for ObjectJsonWriter.

- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/Types.java
- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
Previously, the ClassJsonAdapter saw the platform type and gave its `IllegalArgumentException: Platform {type} annotated {annotations} requires explicit JsonAdapter to be registered`.
If the platform types are allowed but are just not caught by an adapter because they are qualified, they should fall through to the "no adapter found" Moshi error.
> Improve error message for qualified platform types

- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
Should `duplicateKeysAllowedInCustomType()` fail, though?
> Add tests for duplicate JSON keys

- moshi/src/main/java/com/squareup/moshi/Types.java
- moshi/src/test/java/com/squareup/moshi/TypesTest.java
This is useful for JsonAdapter factories.
From https://github.com/square/moshi/pull/236/files#r98377813
The method is a little weird because it is both `hasJsonQualifier` (null means false) and `nextAnnotations`.
~~Maybe this method should not also be `hasJsonQualifier`, though. Maybe this method should just throw an IllegalArgumentException instead of returning null?
The combination of these two methods is not a real performance (`annotations.contains(jsonQualifier)` is O(1)) or simplicity gain.~~
Edit: wasn't thinking, forgetting that we don't have the jsonQualifier instance.
> Add Types.nextAnnotations

- moshi/src/main/java/com/squareup/moshi/JsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/ObjectJsonWriter.java
- moshi/src/test/java/com/squareup/moshi/ObjectJsonWriterTest.java
Previously we'd retain whatever types the caller passed in. This was
potentially problematic for non-immutable numeric types like AtomicInteger.
> Use BigDecimal to encode exotic number types.

- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
createFieldBindings should not take the allowed platform types into
account.
Uh, so this isn't effectively a problem, and I'm nitpicking my change and improving readability. Figured I'd post here, anyway!
https://github.com/NightlyNexus/moshi/blob/e43252582ab74fe578a15591a683d5e5582d1a40/moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java#L83 should not create bindings for private fields of these allowed platform types.
This isn't effectively a problem because the StandardJsonAdapters factory is installed first, and a lot of other things would break before this could ever be a problem.
> Fix isPlatformType

- CHANGELOG.md
Types.createJsonQualifierImplementation() is not in the public API.
> Remove package API from README

- kotlin/src/main/java/com/squareup/moshi/KotlinJsonAdapter.kt
- kotlin/src/test/java/com/squareup/moshi/KotlinJsonAdapterTest.kt
When writing nulls we omit them, and when a value is omitted we assume
it is null.
> Handle nulls symetrically in KotlinJsonAdapter.

- moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.java
- moshi/src/test/java/com/squareup/moshi/JsonUtf8ReaderTest.java
Updates logic from https://github.com/google/gson/issues/1053
> Treat negative zero as a number, not a long.

- kotlin/src/main/java/com/squareup/moshi/KotlinJsonAdapter.kt
- kotlin/src/test/java/com/squareup/moshi/KotlinJsonAdapterTest.kt
Since `FACTORY` was defined inside the companion object of the `internal` class `KotlinJsonAdapter`, it was inaccesible from Kotlin modules other than `moshi-kotlin`. I've fixed this by making it a top-level singleton `object`.
> Fix Factory visibility

- moshi/src/main/java/com/squareup/moshi/Types.java
- moshi/src/test/java/com/squareup/moshi/TypesTest.java
I get the feeling this was not supposed to work at some point, or I am misunderstanding something.
> Fix Types.equals for arrays.

- moshi/src/main/java/com/squareup/moshi/JsonAdapter.java
- moshi/src/test/java/com/squareup/moshi/JsonAdapterTest.java
Fail when creating the JsonAdapter rather than when using it.
> Throw NPE for null indent string in factory method.

- kotlin/src/main/java/com/squareup/moshi/KotlinJsonAdapter.kt
- kotlin/src/test/java/com/squareup/moshi/KotlinJsonAdapterTest.kt
This makes it possible to have synthetic properties that have no
state.
Also test properties that are synthetic and have no backing field.
Closes: https://github.com/square/moshi/issues/299
> Support more kinds of properties in KotlinJsonAdapter

- adapters/pom.xml
Because multiple modules share a package we need to share the dependency on
everything in package-info.java.
> Fix Javadoc builds with the jsr305 dependency.

- moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java
- moshi/src/test/java/com/squareup/moshi/ObjectAdapterTest.java
Previously if we ever had an opaque Object, the content of this object
would always only use the built-in adapters for its members.
This changes the built-in Object adapter to do one layer of type checking
and then to delegate to user-supplied adapters.
The big upside of this is that application code can now change the default
numeric type to use when decoding an untyped object. Typically this will
be used to replace our default of Double with a user-specified numeric type
like BigDecimal.
> Change the adapter for Object.class to delegate.

- adapters/src/main/java/com/squareup/moshi/Iso8601Utils.java
On a personal note, I see lots of "Not an RFC 3339 date" for valid dates like 2017-06-16T22:05:55-07:00 in production on the app I work on.
My only hunch now is that there may be trailing whitespace in the JSON string that my logging tool is trimming (seems unlikely but possible).
I hope this can help me track down server bugs.
> Add cause to malformed date string exception.

- moshi/src/main/java/com/squareup/moshi/Moshi.java
- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
I am concerned someone might misuse Types.nextAnnotations (nullable return type) and get the error deeper in another Factory's usage (like in StandardJsonAdapters.FACTORY) which could be confusing.
> Fail earlier with null annotation set.

- kotlin/src/main/java/com/squareup/moshi/KotlinJsonAdapter.kt
This fails already in Types.getRawType, but a compiler error is preferable.
> JsonAdapter.Factory.create rejects the null Type.

- README.md
Resolves #320 and the general fact that moshi-kotlin is undocumented, highlighted somewhat in issue #315 
@swankjesse I could not predict the wording and order of where the documentation should go in the README, or the wording, so just let me know and I can tweak as needed.
I think it's important to document the existence of moshi-kotlin right now even if it is not as ideal as it could be with the reliance on `kotlin-reflect`. Side-note: I believe @Takhion is creating a library that could potentially be a drop in solution for reading the Kotlin metadata here: https://github.com/Takhion/kotlin-metadata But I suppose that is somewhat unrelated to this PR 😄
> Add moshi-kotlin documentation

- README.md
Hopefully, this will save others from the 3+ hours of ProGuard hell I just dredged through. 
Looks like annotations meant for `@JsonQualifier` were getting stripped by ProGuard, which does not cause builds to fail, so it is extremely subtle. It also would not cause runtime errors all the time, just for specific cases, such as if you had two `java.util.Date` formats, like so:
```
new Moshi.Builder()
.add(new DashDateAdapter())
.add(new SlashDateAdapter())
.build();
```
It would presumably fail to find the annotations, and would just use DashDateAdapter for all `java.util.Date`s, since it is added to Moshi first. Therefore the error would typically come from that adapter trying to parse a date that is meant for another adapter entirely. 
The rule is a derivation of one I found for …
> Add ProGuard rule for JsonQualifier

- examples/src/main/java/com/squareup/moshi/recipes/CustomAdapterWithDelegate.java
When writing a custom adapter recently, I was a bit confused about how to go about making one which does some logic and then delegates the rest as usual - so thought it would be worth contributing a sample.
I reused the example which I also [blogged about](https://medium.com/@emmaguy/creating-a-custom-type-adapter-for-moshi-ae7e1cf469a9). I named the file based on what it is, not sure if there's a convention for them though.
I have signed the CLA! 💪
> Add an example custom Adapter which delegates

- moshi/src/main/java/com/squareup/moshi/JsonAdapter.java
This helps Error Prone and the IDE find accidental usages of toJson(value) instead of toJson(writer, value).
> Add CheckReturnValue for toJson's string result.

- moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java
- moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java
Closes #346.
Builds on #272.
I don't have a real use case for this, but it could be surprising that some delegation works and some doesn't.
> Allow delegates for intermediates in adapters.

- README.md
If you add a custom Kotlin JsonAdapter factory after the KotlinJsonAdapterFactory, you're going to have a bad time.
</br>
see #351
I think my app code is going to have a function like:
```kotlin
fun withKotlinJsonAdapterFactories(moshi: Moshi): Moshi =
moshi.newBuilder().add(KotlinJsonAdapterFactory()).build()
```
</br>
Feel free to better the explanation.
> Document adding the KotlinJsonAdapterFactory.

- kotlin/src/main/java/com/squareup/moshi/KotlinJsonAdapter.kt
- kotlin/src/test/java/com/squareup/moshi/KotlinJsonAdapterTest.kt
Otherwise, the error message is misleading: "No property for required constructor $parameter"
> Clarify error message for transient parameters.

- moshi/src/main/java/com/squareup/moshi/Types.java
- moshi/src/test/java/com/squareup/moshi/TypesTest.java
Also, add a test for the requirement.
References #391.
> Add error message for accidental primitive usage.

- moshi/src/main/java/com/squareup/moshi/JsonValueReader.java
- moshi/src/test/java/com/squareup/moshi/JsonUtf8ReaderTest.java
- moshi/src/test/java/com/squareup/moshi/JsonValueReaderTest.java
This adds parity with JsonUtf8Reader and lets big number literals in JSON be read in as strings in Java.
PR note:
```java
Moshi moshi = new Moshi.Builder().build();
JsonAdapter<String> adapter = moshi.adapter(String.class);
JsonReader reader = JsonReader.of(new Buffer().writeUtf8("9223372036854775808"));
String bigMoney = adapter.fromJsonValue(reader.readJsonValue());
```
This change will make the above work (instead of throwing, expecting a double), so that you can use big numbers in polymorphic adapters where you need to read in the map.
Closes #388.
> Let JsonValueReader.nextString read numbers.

- moshi/src/main/java/com/squareup/moshi/JsonValueReader.java
- moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java
Make JsonValueReader.selectString return -1 for non-strings instead of throwing.
> Make selectString consistent across JsonReaders.

- moshi/src/main/java/com/squareup/moshi/JsonReader.java
JsonReader.Token is less redundant than Gson's JsonReader.JsonToken.
> Fix doc reference to Token.

- kotlin/src/main/java/com/squareup/moshi/KotlinJsonAdapter.kt
- kotlin/src/test/java/com/squareup/moshi/KotlinJsonAdapterTest.kt
Instead of throwing an InvocationTargetException.
> Clarify error for non-null Kotlin properties.

- README.md
See #438 for the use case. The documentation was not accurate enough IMO. Thus, mention that KotlinJsonAdapterFactory is required for validation.
> mention that KotlinJsonAdapterFactory validates

- kotlin/src/main/java/com/squareup/moshi/kotlin/KotlinJsonAdapter.kt
- kotlin/src/test/java/com/squareup/moshi/kotlin/KotlinJsonAdapterTest.kt
IllegalArgumentException was the best exception type I could think of.
> Crash earlier for property type conflicts.

- moshi/src/main/java/com/squareup/moshi/Moshi.java
- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
This just happened to me because I wasn't null checking the result of `Types.nextAnnotations`. might as well fail here instead of in Moshi.cacheKey.
> Disallow null annotation set in adapter lookup.

- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/AdapterGenerator.kt
- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/MoshiKotlinCodeGenProcessor.kt
- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/PropertyGenerator.kt
- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/kotlintypes.kt
- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/metadata.kt
Move more behavior into the types: Adapter and Property now have many
instance methods and are now mutable value classes rather than immutable
data classes.
This changes how some of the bookkeeping code works. Previously there were
some pretty tricky types: maps with pairs as keys, indexed and non-indexed
lists of properties. With this change more of the logic operates directly
on the properties.
> Split the MoshiKotlinCodeGenProcessor into multiple types.

- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/AdapterGenerator.kt
- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/JsonClassCodeGenProcessor.kt
- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/PropertyGenerator.kt
Part of #461
This leverages AutoCommon's `GeneratedAnnotations#generatedAnnotation` API to generate a `@Generated` annotation where possible. This keeps with conventions in other code gen tools, and also allows for more fine grained proguard rules for keeping generated adapter names, like so:
```proguard
-keepnames @com.squareup.moshi.<wherever this ends up>.MoshiSerializable class *
-keepnames @javax.annotation.Generated class **JsonAdapter
-keepnames @javax.annotation.processing.Generated class **JsonAdapter
```
Generated annotation looks like this:
```kotlin
@Generated(
value = ["com.squareup.moshi.MoshiKotlinCodeGenProcessor"],
comments = "https://github.com/square/moshi"
)
```
I think this should be able to replace the `”Generated code; do not edit“ header` item in the linked issue …
> Generate `@Generated` annotation onto adapters when possible

- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/JsonClassCodeGenProcessor.kt
- moshi/src/main/java/com/squareup/moshi/JsonAdapter.java
- moshi/src/test/java/com/squareup/moshi/JsonAdapterTest.java
This adapter modifier throws exceptions if an unexpected null is
encountered. This may pair nicely with Kotlin.
> JsonAdapter.nonNull() forbids explicit nulls in the JSON body

- kotlin-codegen/integration-test/src/test/kotlin/com/squareup/moshi/KotlinCodeGenTest.kt
- kotlin/src/test/java/com/squareup/moshi/kotlin/KotlinJsonAdapterTest.kt
- moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.java
- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/Moshi.java
- moshi/src/main/java/com/squareup/moshi/internal/Util.java
- moshi/src/test/java/com/squareup/moshi/AdapterMethodsTest.java
- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
In the very common case, there are no JsonQualifier annotations for the type.
Closes #456
> Make "no adapter" error message friendlier.

- moshi/src/main/java/com/squareup/moshi/internal/Util.java
Moshi.Builder.add(Type, ...) adds a factory that had a broken type equality check.
Closes #128 
Could also canonicalize the input of the add methods instead, but I like getting rid of j.l.r.Type.equals.
Confirmed broken and fixed states on an Android SDK 22 emulator.
> Fix type checks with custom adapters.

- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/JsonClassCodeGenProcessor.kt
- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/PropertyGenerator.kt
- kotlin-codegen/compiler/src/test/java/com/squareup/moshi/CompilerTest.kt
- kotlin-codegen/integration-test/src/test/kotlin/com/squareup/moshi/GeneratedAdaptersTest.kt
- kotlin-codegen/integration-test/src/test/kotlin/com/squareup/moshi/KotlinCodeGenTest.kt
Currently our main loop to gather PropertyGenerators goes over the backing fields.
This needs to change to iterate over the properties themselves. That leads to a lot
of churn. The net result is slightly more compatibility with the reflective adapter.
> Support properties that don't have a backing field.

- kotlin-codegen/compiler/src/test/java/com/squareup/moshi/CompilerTest.kt
- kotlin-codegen/compiler/src/test/java/com/squareup/moshi/KotlinCompilerCall.kt
This also adds a smoke test to check for generated type errors.
> Add apoptions support in KotlinCompilerCall

- moshi/src/main/java/com/squareup/moshi/Moshi.java
- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
Otherwise, Moshi.adapter(null) will end up calling into user JsonAdapter factories with a null Type parameter.
Kotlin fails with java.lang.IllegalArgumentException: Parameter specified as non-null is null
That message ends up too far away from the real error.
> Disallow null Type from entering user code.

- moshi/src/main/java/com/squareup/moshi/JsonUtf8Writer.java
- moshi/src/main/java/com/squareup/moshi/JsonValueWriter.java
- moshi/src/test/java/com/squareup/moshi/MapJsonAdapterTest.java
- moshi/src/test/java/com/squareup/moshi/PromoteNameToValueTest.java
Closes #277.
We could pass in the class name from the map adapter, but this error message is clear enough without adding more complexity. (Correct me if I'm wrong, of course.)
> Add coherent error message for uneconded map keys.

- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/AdapterGenerator.kt
- kotlin-codegen/integration-test/src/test/kotlin/com/squareup/moshi/GeneratedAdaptersTest.kt
- kotlin/src/test/java/com/squareup/moshi/kotlin/KotlinJsonAdapterTest.kt
instead of falling down to "Required property 'a' missing at $"
> Fix error message for assigning to non-null properties.

- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/AdapterGenerator.kt
- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/DelegateKey.kt
- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/JsonClassCodeGenProcessor.kt
- kotlin-codegen/compiler/src/test/java/com/squareup/moshi/CompilerTest.kt
- kotlin-codegen/integration-test/src/test/kotlin/com/squareup/moshi/GeneratedAdaptersTest.kt
- moshi/src/main/java/com/squareup/moshi/Types.java
- moshi/src/test/java/com/squareup/moshi/TypesTest.java
This implements full `JsonQualifier` support in the kotlin codegen. This works via reflection, copying qualifier annotations directly onto the generated adapter and retrieving them reflectively from the adapter via new helper utility method in `Types`.
Note that this requires the given qualifiers to be applicable to `FIELD` site targets, as we use that to avoid generation of an unnecessary synthetic method in the kotlin compiler for it to store the annotations and also know exactly how to access the annotations, vs guessing where the kotlin compiler will put them or what the name of the synthetic method is. 
Resolves another part of #461
> Full JsonQualifier support in kotlin codegen

- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/DelegateKey.kt
- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/metadata.kt
- kotlin-codegen/integration-test/src/test/kotlin/com/squareup/moshi/GeneratedAdaptersTest.kt
We were forgetting to apply the property's nullability to the resolved type.
Fixes #521
> Fix nullable properties of TypeVariable types

- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/TypeResolver.kt
- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/kotlintypes.kt
- kotlin-codegen/compiler/src/main/java/com/squareup/moshi/metadata.kt
- kotlin-codegen/compiler/src/test/java/com/squareup/moshi/TypeResolverTest.kt
This fixes #526 and also cleans up some `typeVariable` name shadowing in `metadata.kt` that was causing some confusing behavior before.
> Fix nullability not being preserved and clean up from shadowed names

- README.md
- kotlin/codegen/pom.xml
That way we won't collide with other annotation processors if they have an
incompatible version.
> Shade unreleased KotlinPoet 0.7.0.

- README.md
`-keepnames` will prevent Proguard from renaming the class during obfuscation phase but won't protect the class from code shrinking. ([source from Proguard manual](https://www.guardsquare.com/en/proguard/manual/usage#keepnames))
In most cases, the generated adapter classes are never referenced directly in the code as the adapters are loaded dynamically by Moshi.
This means that, for Proguard, the classes are unused and Proguard will remove them during the shrinking phase.
The adapters need to be kept as well as there primary constructor. This is the best configuration I figured out.
Thank you for this great new feature.
> Update Proguard configuration for codegen

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/TargetType.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt
We had a missing `resolveAliases` check when gathering argument lists 🙄 
This is important because the argument is on the backing type, not on the aliased one.
As part of it, I also reworded the API to be a bit more understandable. Now instead of the confusing `resolveAliases` and always being negated when used with `hasAbbreviatedType()`, it's called `useAbbreviatedType` (which matches how it's referred to in the kotlin compiler as well).
Resolves #547
> Fix generic typealiases

- adapters/src/main/java/com/squareup/moshi/adapters/RuntimeJsonAdapterFactory.java
- adapters/src/test/java/com/squareup/moshi/adapters/RuntimeJsonAdapterFactoryTest.java
I made this simple instead of flexible.
This is slightly different from Gson's RuntimeJsonAdapterFactory.
It doesn't remove the type value when deserializing and add it when serializing because I don't know why it should. Let me know if there's a use case or if consistency with Gson is important.
> Add RuntimeJsonAdapterFactory to adapters module.

- moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java
- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
"at path $[1]" > "at path $[0]"
> Fix incorrect path in enum adapter error message.

- README.md
Sonatype changed its site.
I'm not sure if there's a way to link directly to the latest jar now.
> Fix README link to jar.

- README.md
- kotlin/reflect/src/main/resources/META-INF/proguard/moshi-kotlin.pro
- moshi/src/main/resources/META-INF/proguard/moshi.pro
This should probably not be merged until AGP 3.2.0 is out, because the `-if` rule used for generated adapters is only supported in ProGuard 6.0.0+ (AGP 3.1.x uses ProGuard 5.x).
> Embed ProGuard rules in the jar

- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt
We had a bug report that said using just @ToJson wasn't working.
This test attempts to show it should work just fine.
https://github.com/square/moshi/issues/545
> Confirm you can use codegen with adapter methods

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/DelegateKey.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/PropertyGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/TargetProperty.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt
AnnotationSpec implements equals() in the way we need, but
AnnotationMirror doesn't. As a consequence this fixes a problem
where we were generating redundant adapters.
Closes: https://github.com/square/moshi/issues/563
> Change DelegateKey to use AnnotationSpec instead of AnnotationMirror

- adapters/src/main/java/com/squareup/moshi/adapters/EnumJsonAdapter.java
- adapters/src/main/java/com/squareup/moshi/adapters/RuntimeJsonAdapterFactory.java
- adapters/src/test/java/com/squareup/moshi/adapters/RuntimeJsonAdapterFactoryTest.java
Otherwise the adapter is not symmetric.
> Include labels when encoding with RuntimeJsonAdapterFactory.

- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt
I couldn't reproduce the reported issue.
Closes: https://github.com/square/moshi/issues/574
> Test support for uppercase property names

- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
- moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java
This is in alignment with the lookup for Java and Kotlin reflective adapters.
This also makes https://github.com/square/moshi/issues/586 easy to support, as long as adapter factories don't know about type nullability.
> Make generated adapters null-safe.

- moshi/src/main/java/com/squareup/moshi/ClassFactory.java
- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java
- moshi/src/main/java/com/squareup/moshi/internal/Util.java
Otherwise we end up with many InvocationTargetExceptions layered in, which makes
it difficult to identify what actually failed.
> Generate nicer stacktraces when creating a generated adapter fails.

- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/Moshi.java
- moshi/src/test/java/com/squareup/moshi/JsonQualifiersTest.java
- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
This allows for an error message that includes field names to track down the cause of adapter creation failure for deeply nested structures.
This got complicated, so I am not sure I have a good solution yet.
> Track field names in the adapter lookup stack.

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/DelegateKey.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
Delegate to installed adapters instead of checking for null.
Closes #586.
> Allow user adapters to convert null to non-null in codegen.

- moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.java
Cleanup of a rare code path for block comments in lenient readers.
> Use BufferedSource.indexOf instead of loops.

- adapters/src/main/java/com/squareup/moshi/adapters/RuntimeJsonAdapterFactory.java
We don't yet have the behavior we want for looking ahead at the type label.
> Hide RuntimeJsonAdapterFactory for the forthcoming release.

- kotlin/codegen/pom.xml
The version is already defined in the root.
> Remove duplicate kotlin-metadata version declaration.

- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt
It makes IntelliJ grumpy.
https://youtrack.jetbrains.com/issue/KT-27224
> Don't use @Language when the literal includes a dollar sign

- moshi/src/main/resources/META-INF/proguard/moshi.pro
We need to keep enum fields for `EnumJsonAdapter` even if they are not used elsewhere.
```kotlin
@JsonClass(generateAdapter = false)
enum class StatusCode {
@Json(name = "success")
Success,
@Json(name = "error")
Error
}
if (status == StatusCode.Success) {
...
}
```
`-keepclassmembernames` won't prevent `StatusCode.Error` from being removed that's why `-keepclassmembers` should be used instead.
@gabrielittner
> Always keep fields of annotated enums

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessor.kt
Someone at KotlinConf brought this to my attention, as they're trying to generate their own adapter factory that delegates to the other ones (to skip the reflective lookup) but can't since moshi consumes the annotation and doesn't allow others.
> Allow other processors to process JsonClass

- adapters/src/main/java/com/squareup/moshi/adapters/RuntimeJsonAdapterFactory.java
- adapters/src/test/java/com/squareup/moshi/adapters/RuntimeJsonAdapterFactoryTest.java
Instead use our new flatten API to decode directly to the stream.
> Don't decode into memory in RuntimeJsonAdapterFactory

- adapters/src/main/java/com/squareup/moshi/adapters/RuntimeJsonAdapterFactory.java
RuntimeJsonAdapterFactory was public in a previous 1.7-SNAPSHOT build.
After viewing the todo, I changed the visibility modifier ahead of the next 1.8 snapshot release.
> Make RuntimeJsonAdapterFactory public

- moshi/src/main/java/com/squareup/moshi/Moshi.java
- moshi/src/test/java/com/squareup/moshi/DeferredAdapterTest.java
This changes how we lookup and cache adapters. Previously we were pretty
optimistic about putting adapters in the cache; these adapters could have
depended upon stubs that were incomplete.
Now we're a lot more careful: we only put adapters in the cache if the
root object that triggered a set of recursive calls was constructed
successfully.
Closes: https://github.com/square/moshi/issues/679
> Fix a race condition on deferred adapters

- kotlin/codegen/pom.xml
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/DelegateKey.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/TargetProperty.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/TypeRenderer.kt
Also, use KotlinPoet's escaping for $ characters in formatted strings.
This is partly a revert of 01f600c (https://github.com/square/moshi/pull/604/).
> Update to KotlinPoet 1.0.0-RC2.

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/TypeRenderer.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt
> Use javaObjectType instead of Java primitives while creating parametrized type

- kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt
- kotlin/reflect/src/main/test/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
- moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java
- moshi/src/main/java/com/squareup/moshi/internal/Util.java
This is handy for development builds where kapt is disabled and models still have @JsonClass(generatedAdapter = true).
Closes #715
> Fall back to reflection when generated adapter is not found.

- README.md
This will add the Gradle kotlin dsl to the README.
TBH I'm not quite sure with the syntax.
I also tried the following but wasn't very happy about:
Groovy DSL
```groovy
implementation 'x.y.z:moshi:version'
```
Kotlin DSL
```kotlin
implementation("x.y.z:moshi:version")
```
So I decided to pack everything in **one code block**.
> Add Gradle Kotlin DSL for dependencies

- adapters/src/main/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactory.java
- adapters/src/test/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactoryTest.java
This works now.
Using general types like Object, Map, or List for the base type is error-prone, but the checks for these cases are not worth the code cost.
> Allow Object base type for PolymorphicJsonAdapterFactory.

- moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.java
- moshi/src/main/java/com/squareup/moshi/JsonValueReader.java
- moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java
Fail with a clear message. This is useful when iteratoring through an array, making assumptions about the size without using hasNext.
Also, disallow calling skipValue at the end of a document. This is a behavior change.
> Fix infinite loop when calling skipValue at the end an object or array.

- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
Resolves #748
There are two existing tests that fail with this now, let me know what you all want to do with them (migrate/adjust/delete/etc)
`KotlinJsonAdapterTest#delegatesToInstalledAdaptersBeforeNullChecking`
`KotlinJsonAdapterTest#nullablePrimitivesUseBoxedPrimitiveAdapters`
> Refuse kotlin classes in ClassJsonAdapter

- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/Types.java
- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
The error message about platform types will never contain qualifiers.
Also, simplify platform type check.
> Improve error message for platform types.

- README.md
Null safety is an important feature of the Kotlin language. The fact that Moshi supports wrapping existing adapters in a null safe or non-null variant is important for null safety. Therefore it makes sense to promote this feature in the readme, as this is one of the first places people should look for support and such features.
> Add section about null safety

- adapters/src/main/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactory.java
- adapters/src/test/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactoryTest.java
Picking from #741
Resolves #739 
Example usage:
```java
Error fallbackError = new Error(Collections.<String, Object>emptyMap());
Moshi moshi = new Moshi.Builder()
.add(PolymorphicJsonAdapterFactory.of(Message.class, "type")
.withSubtype(Success.class, "success")
.withSubtype(Error.class, "error")
.withDefaultValue(fallbackError))
.build();
```
> Add support for default values in PolymorphicJsonAdapterFactory

- kotlin/codegen/pom.xml
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/TypeResolver.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/kotlintypes.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/LooksLikeAClass/ClassInPackageThatLooksLikeAClass.kt
- Update KotlinPoet to 1.0.1
- Drop `asNullableIf` in favor of the plain `copy()` functions
- Add a test for #783
> Some miscellaneous kotlinpoet updates

- adapters/src/main/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactory.java
- adapters/src/test/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactoryTest.java
Before, this would fail when skipping to find the index of the label.
Note that this still requires the type to have a label field.
> Support fail on unknown in PolymorphicJsonAdapterFactory.

- kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
Before, the KotlinJsonAdapter threw "java.lang.IndexOutOfBoundsException: Index: 0, Size: 0" on a duplicate key when the key matched a property that was not a constructor parameter.
> Correct error for duplicate JSON key for Kotlin.

- adapters/src/main/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactory.java
It doesn't have an effect now, but this is for the future when closing the peeked source also clears buffers.
> Unconditionally close the peeked JsonReader.

- .gitignore
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessor.kt
- kotlin/tests/pom.xml
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest_CustomGeneratedClassJsonAdapter.kt
- moshi/src/main/java/com/squareup/moshi/JsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/JsonClass.java
- moshi/src/main/java/com/squareup/moshi/Types.java
- moshi/src/main/java/com/squareup/moshi/internal/NullSafeJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/internal/Util.java
- moshi/src/test/java/com/squareup/moshi/JsonAdapterTest.java
- moshi/src/test/java/com/squareup/moshi/TypesTest.java
This implements support for custom generators via `@JsonClass(generator = "")`. The goal is to allow custom generators to plug in to the same adapter lookup that Moshi supports for its own code gen.
Example:
```kotlin
package example
@JsonClass(generateAdapter = true, generator = "custom")
data class Taco(val seasoning: String)
```
In this event, Moshi codegen will skip generation of a `example.Taco` adapter, but at runtime will expect to find one at `example.TacoJsonAdapter` (via extracted `Types#generatedJsonAdapterName()` API)
This opens up a few opportunities:
- Custom generators. 3rd party JsonAdapter-generating libraries like auto-value-moshi, kotshi, etc could hook into this to allow for zero-configuration usage.
- Custom aggregators could generate reflection-less adapters via …
> Allow custom generators

- adapters/src/main/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactory.java
- adapters/src/test/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactoryTest.java
There can be use cases where different type labels should match with the same subtype
> removed limitation where subtypes should be unique

- .buildscript/deploy_snapshot.sh
- .travis.yml
oraclejdk8 isn't available unless we ust trusty dist, which is also an option
> Switch to openjdk8 for travis builds

- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
- moshi/src/test/java/com/squareup/moshi/MoshiTest.java
We only check the raw type here, so the message should match
Example case - in #875 a `Triple<*, *, *>` would yield an error message that `kotlin.Triple<java.lang.Object, java.lang.Object, java.lang.Object>` required an adapter, which doesn't tell you immediately which type it was confused on
> Pass raw type rather than possibly-generic type in platform type error

- kotlin/reflect/pom.xml
- kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/-MoshiKotlinExtensions.kt
- kotlin/reflect/src/main/test/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
- kotlin/tests/pom.xml
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codgen/GeneratedAdaptersTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
- moshi/src/main/java/com/squareup/moshi/JsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/internal/NonNullJsonAdapter.java
- moshi/src/test/java/com/squareup/moshi/JsonAdapterTest.java
This implements two helper APIs that leverage reified types + `typeOf()` to simplify adapter lookup and builder construction.
Note that this requires a manual implementation of `KType.toType()` as the stdlib's `javaType` reflect property isn't actually implemented.
One test fails because of a mismatched error message, which actually revealed a bug that I'll PR separately to fix.
An interesting point of discussion is how to handle the `@ExperimentalStdLibApi` annotation. I think it's fair to expose it with that annotation transitively applied, and basically not support it until it's graduated from experimental
> Kotlin-reflect QoL APIs

- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/internal/Util.java
This adds kotlinx to the exclusion list, and also updates the doc on ClassJsonAdapter
> Don't reflect on kotlinx and update doc

- kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt
Misc idiomatic cleanups, nothing functional changing
> Clean up warnings in KotlinJsonAdapter

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/PropertyGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/TargetProperty.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/kotlintypes.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DefaultConstructorTest.kt
- moshi/src/main/java/com/squareup/moshi/internal/Util.java
- moshi/src/main/resources/META-INF/proguard/moshi.pro
This switches code gen to be able to dynamically invoke constructors and indicate which parameters are not set. No more need for the `copy()` trick! Now full dynamic default values are supported as well.
Caveat: This uses reflection to look up the synthetic defaults constructor that kotlinc generates for these types. Its signature is the original constructor + two extra parameters: one `mask` int parameter that's used to indicate which parameter values are set, and one throwaway `DefaultConstructorMarker` just used to differentiate it. This latter type is also what we use to find this constructor. The reflection is cached, and should be simple to set up with proguard (have pinged proguard folks separately to see if we can just match on that `DefaultConstructorMarker` parameter). …
> Support dynamic defaults constructor invocation in kotlin code gen without kotlin-reflect

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/AdapterGenerator.kt
- moshi/src/main/java/com/squareup/moshi/internal/Util.java
This simplifies generated code quite a bit, and just uses a simple String.format rather than stringbuilder + avoiding string allocations
Before/after: https://gist.github.com/ZacSweers/90a4fb102ee6b9da1c5347f50b81d6af
> Refactor missing/null properties to helper utils instead

- adapters/src/main/java/com/squareup/moshi/Rfc3339DateJsonAdapter.java
- adapters/src/main/java/com/squareup/moshi/adapters/Rfc3339DateJsonAdapter.java
- adapters/src/test/java/com/squareup/moshi/adapters/Rfc3339DateJsonAdapterTest.java
Resolves #723, also opportunistically makes the deprecated type's delegate private and final
CC @benjamin-bader @chrisjenx
> Make Rfc3339DateJsonAdapter null-safe

- moshi/src/main/java/com/squareup/moshi/Types.java
- moshi/src/test/java/com/squareup/moshi/TypesTest.java
It's programmer error to omit this, but vararg declaration allows you to. This checks that.
We could improve it to ensure matching lengths or bounds, but this is a good start.
Helps clarify cases like #931
> Throw on missing type variables in Types.newParameterizedType* methods

- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
The fix for #922 is part of #903. The backend rework seems to have done the trick :wink: 
This PR just adds a test case.
> added test for transient delegate in kotlin code gen (#922)

- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
Test for #921, the fix for the bug seems to be part of #903
> added test for internal property without backing field (#921)

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/PropertyGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/TargetParameter.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/TargetProperty.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
This fixes an issue for an edge case where parameter `@Json` annotations defined with `@field:` site targets always use the parameter name rather than the actual Json `name` annotation value for the property. With `field:` site targets, this annotation would only come up in reading the property annotations.
This would happen because the `TargetParameter#jsonName` property would default to the parameter name. While the `TargetProperty` annotations later would have the correct value, it would yield to the parameter every time since it said it had a value (it only checked nullability, even though the property wasn't nullable!). This fixes that by just denoting an absent `@Json` name definition by making the `jsonName` properties in both target classes nullable, and only falling back to the …
> Fix `@field:Json` parameters annotations always taking precedence

- moshi/src/main/java/com/squareup/moshi/Types.java
- moshi/src/main/java/com/squareup/moshi/internal/Util.java
- moshi/src/test/java/com/squareup/moshi/RecursiveTypesResolveTest.java
- moshi/src/test/java/com/squareup/moshi/TypesTest.java
- moshi/src/test/java/com/squareup/moshi/internal/RecursiveTypesResolveTest.java
This fixes two related issues, one documented in #338. Both cases are solved borrowing the Gson solutions for them, since all the code/logic around wildcard types for them are borrowed from them as well.
The first is fixing recursion in `Util#sub/supertypeOf` using the solution from https://github.com/google/gson/commit/a300148003e3a067875b1444e8268b6e0f0e0e02. This is a bugfix itself, but also necessary for the next issue.
The second is fixing recursion in `Types#resolve()` by tracking previously visited type variables using the solution from https://github.com/google/gson/pull/1128
Resolves #338
> Fix TypeVariable/WildcardType recursion causing stackoverflows

- kotlin/tests/pom.xml
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
This was discussed in #776. The fix is really simple. I also added tests since I am using this in my own projects. 
I'm not sure if you want to pull this into master before inline classes become stable. To run the tests I enabled inline classes for the moshi-kotlin-test module. Also I don't think this will break unless they change the protobuff flag in the metadata declaring a class to be inline, which I think is very unlikely. 
Also this might not fix #776 completely since I haven't looked into using inline classes with the reflection based adapter.
___
For everyone else finding this, if this isn't merged into master [here](https://jitpack.io/#Wasabi375/moshi/inline_class-SNAPSHOT) is a link to jitpack where you can get the current version of the build. I will try to keep this up with …
> Added codegen support for inline classes

- moshi/src/main/java/com/squareup/moshi/JsonScope.java
- moshi/src/main/java/com/squareup/moshi/JsonUtf8Writer.java
- moshi/src/main/java/com/squareup/moshi/JsonValueWriter.java
- moshi/src/main/java/com/squareup/moshi/JsonWriter.java
- moshi/src/test/java/com/squareup/moshi/JsonWriterTest.java
- moshi/src/test/java/com/squareup/moshi/PromoteNameToValueTest.java
Unlike `value(BufferedSource)`, this retains the push-based nature of JsonWriter and allows layering other sinks (such as a base64-encoding Sink for binary data). Since `value(BufferedSource)` is trivially replaced by reading the source into the value sink, it is deprecated.
Potentially helps out #100 a bit.
> Add JsonWriter.valueSink for streaming data

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
This optimizes `toString()` functions to emit separate strings for the enclosing prefix and the adapter name
Example:
```kotlin
override fun toString(): String = buildString {
append("GeneratedJsonAdapter(").append("SmokeTestType").append(")") }
```
> Generate optimized toString()

- moshi/src/main/resources/META-INF/proguard/moshi.pro
Addresses #962 
I removed the function modifiers mentioned in the issue as they didn't seem to be specifically related to the problem at hand. I also added it to the other enum related rule, rather than using the `enum *` matcher.
One less than ideal thing is that it would keep a hand written unused method with the same signature for Java consumers. I suspect that's a small edge case, but if @JakeWharton or others have a suggestion to improve the rule to avoid it, it could be valuable. As far as I can tell the Kotlin compiler doesn't generate a `synthetic` modifier for the generated method, which seems unfortunate.
> Keep synthesized values() for EnumJsonAdapter

- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/-MoshiKotlinExtensions.kt
We can do a better job of this when we make the core Moshi module
depend on the Kotlin stdlib
> Don't add new public APIs for Kotlin type inference

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt
- kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessorTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
- pom.xml
Fixes #968 
We have to manually unwrap typealiases now, as kotlinpoet now (correctly) reports the aliases and just leaves a tag to retrieve the underlying type as needed.
> Update to KotlinPoet 1.4.2

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt
- kotlin/reflect/src/main/test/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
- moshi/src/main/java/com/squareup/moshi/internal/Util.java
This fixes #975 by directly looking up the constructor via `getDeclaredConstructors` and the exact parameter types + mask and default constructor marker.
> Fix support for classes w/ multiple constructors in code gen

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/TargetConstructor.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/TargetParameter.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/MultipleMasksTest.kt
This adds a `FromJsonComponent` sealed type for describing the combination of properties, parameters, and parameter properties. This allows us to handle parameter-only types separately (needed for mask index calculation). Resolves #979
Same suggestions welcome... I couldn't think of what else to call this.
> Handle non-property parameters in kotlin code gen

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/TypeRenderer.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt
- kotlin/tests/pom.xml
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
This resolves #983 by correctly unwrapping parameterized and wildcard types on top of the classname types we resolve currently. In the process, this also revealed a couple bugs with wildcard rendering that are resolved in 9c12610.
> Fix handling of typealiases in non-classname envs + wildcard fixes

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
Fixes #995 
We need to continue checking for typealiases even when we hit the first `ClassName`!
> Unwrap nested typealiases in code gen

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
`Int?` will not equal `Int` in KotlinPoet, so this was always falling through to the default `::class.java` code.
Resolves #991
> Check against non-nullable known primitives when rendering class blocks

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
We unfortunately regressed here by not propagating nullability to the unwrapped alias or parameterized type.
Resolves #990
> Fix nullable properties

- adapters/src/main/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactory.java
- adapters/src/test/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactoryTest.java
This type explicitly indicates an unknown value. This is an explosive case, but an alternative could be to just write null into the writer?
Resolves #989
> Don't allow toJson() serialization on polymorphic default values

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/-MoshiKotlinExtensions.kt
Resolves #1009. Also fixes a discovered boxed types bug along the way and refactors the type mapping to a new `mapTypes` API for reuse.
> Fix incorrect type variance being applied on generated adapters 

- adapters/src/main/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactory.java
- adapters/src/test/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactoryTest.java
This reverts commit 6323a0b7c82b84c2e9128341533a1399c072b040.
This makes it difficult for a client to take a server-provided value,
modify it, and send it back.
> Revert "Don't allow toJson() serialization on polymorphic default values

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/AppliedType.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessor.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/MoshiCachedClassInspector.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt
- kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessorTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
This resolves #1022 and also became a good opportunity to refactor metadata parsing a bit. This allows us to put a cache in front of it now, which should give us a nice little performance win.
Also added an extra check + test for private classes
> Handle enclosing visibility + cache metadata parsing

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
- kotlin/tests/pom.xml
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
Followup from #1023 (Resolves #1023 too). Since we can't do targeted deprecation suppressions, we can just stick with blanket deprecations suppressions for now. This also suppresses a couple other common issues with all our generated adapters and allows us to re-enable -Werror in tests.
Have just eyeballed the results for now, can add a proper test as a followup once #1014 is in
Example
```kotlin
@Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION")
internal class MismatchParentAndNestedClassVisibilityJsonAdapter(
moshi: Moshi
) : JsonAdapter<MismatchParentAndNestedClassVisibility>() {
```
> Suppress common warnings in generated classes

- moshi/src/main/java/com/squareup/moshi/internal/Util.java
Reported by a Googler - We currently gate the lookup of the class on the presence of `Metadata`. However, `Metadata` might be justifiably stripped by Proguard/R8, even though `DefaultConstructorMarker` might still be present. This means Moshi's defaults invocation is likely broken on (at least) R8 builds without this.
Workaround until next release is to keep Metadata annotations
> Always check for DefaultConstructorMarker class

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
NameAllocator will add underscores to names, which kotlin doesn't like for stylistic reasons
> Add LocalVariableName to common suppressions

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
These were redundant. Was `return Foo<T>(...)` and is now `return Foo(...)`
> Omit unnecessary generic type from standard constructor call

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessor.kt
This shares the classinspector cache across multiple rounds and also refuses to run if the previous round failed in order to reduce possible noise.
> Minor processor cleanups

- moshi/src/main/java/com/squareup/moshi/JsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/Moshi.java
As per #1119.
I've just done Moshi, Moshi.Builder and JsonAdapter. Happy to do more on request.
Note that Moshi.Builder wasn't thread-safe, so I trivially made it so by synchronizing its list of factories.
> Document thread safety

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/ComplexGenericsInheritanceTest.kt
This resolves #1046 by tracking mappings of superclass type vars to their materialized types in subclasses. This is tested with some pathologically complex examples, so hope it's sturdy!
Other small bits:
- This exposes an awkward case where type inference can't be relied upon at construction. We could try to figure this out, but the overhead of determining that at build time outweighs the cost of just being pedantic here, so this effectively reverts #1041. 
- Opportunistic - suppression of `RedundantExplicitType` in known suppressions.
> Fix resolution of types in superclass settable properties

- moshi/src/main/resources/META-INF/proguard/moshi.pro
R8 has [a bug](https://issuetracker.google.com/issues/158454684) where it only honors the _last_ annotation defined in a shrinker rule class specification. This has been fixed in the latest R8, but it will be a while before that reaches stable.
Inverting the order means that the effective rule on affected R8 versions becomes
```
-keepclassmembers @com.squareup.moshi.JsonClass class * {
synthetic <init>(...);
}
```
instead of
```
-keepclassmembers @kotlin.Metadata class * {
synthetic <init>(...);
}
```
Since most (all?) Kotlin classes are annotated with `@Metadata`, the old form would match every synthetic constructor of any Kotlin class. These occur when you use default arguments or on companion objects. In practice we found this rule causes companion object classes to be retained solely …
> Reorder annotations in shrinker rule to minimize R8 bug

- moshi/src/main/java/com/squareup/moshi/internal/Util.java
- moshi/src/main/resources/META-INF/proguard/moshi.pro
R8 now have automatic detection of Class.forName and auto generate keep rules.
This makes application built with Moshi to keep unwanted Kotlin Metadata that have a huge impact on APK size.
After discussion with R8 team, there's currently no solution to avoid this other than using the trick in this PR.
Fixes https://github.com/square/moshi/issues/1115
> Fix R8 keeping all Kotlin metadata when using Moshi.

- adapters/src/main/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactory.java
- adapters/src/test/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactoryTest.java
This PR includes an implementation proposal for #784.
The main idea is to allow users of the `JsonAdapterFactory` to provide a `JsonAdapter` that will deal with the `reader` in case of an unknown/unmapped label.
Doing this has the advantage to give freedom to developers to re-use already existing components and tools to build their logic.
> Extend PolymorphicJsonAdapterFactory to allow custom handling of unknown labels

- adapters/src/main/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactory.java
- adapters/src/test/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactoryTest.java
We don't need a custom JsonAdapter subclass - we can just call through
unconditionally and fail if the type is unexpected.
> Simplify the internals of PolymorphicJsonAdapterFactory

- kotlin/codegen/pom.xml
- kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessorTest.kt
- kotlin/reflect/src/main/resources/META-INF/proguard/moshi-kotlin.pro
- kotlin/tests/pom.xml
- pom.xml
This eliminates the need for the moshi-kotlin proguard rules since kotlin-reflect packages its own now
Resolves #1095
Resolves #345
> Update to Kotlin 1.4.0

- CHANGELOG.md
Some were cherrypicked to 1.9.3, this adds (I think) everything else that's fixed or new in 1.10
> Add missing 1.10 bits to changelog

- moshi/src/main/java/com/squareup/moshi/JsonValueSource.java
- moshi/src/test/java/com/squareup/moshi/JsonValueSourceTest.java
This will read one JSON object and then stop.
This is a part of https://github.com/square/moshi/issues/675
> JsonValueSource: a brace-matching implementation of okio.Source

- moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.java
- moshi/src/main/java/com/squareup/moshi/JsonValueSource.java
- moshi/src/test/java/com/squareup/moshi/JsonUtf8ReaderTest.java
Defer doing I/O until strictly necessary.
Remove some unnecessary branching in doPeek(), which is in the
inner loop of all JSON parsing.
> Small improvements to JsonReader.nextSource

- kotlin/codegen/build.gradle.kts
Fixes #1212. See https://github.com/square/moshi/pull/1213/files#r483707716
> Fix shadow packaging in code gen artifact

- moshi/src/main/java/com/squareup/moshi/JsonReader.java
- moshi/src/main/java/com/squareup/moshi/JsonWriter.java
- moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java
- moshi/src/test/java/com/squareup/moshi/JsonWriterTest.java
Relates to issue #1126.
This is an implementation of a suggestion from @swankjesse (https://github.com/square/moshi/pull/1209#issuecomment-683903925)
This will give developers the ability to append custom data to JsonReader/JsonWriter classes. This will be very useful for custom adapters that wish to track supplemental data.
> Introduced tags to reader/writers

- build.gradle.kts
- settings.gradle.kts
The previous setup said to only look for those packages in jcenter. This is a more powerful alternative, which says only use jcenter for those packages
> Use exclusiveContent API for jcenter

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessor.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/DelegateKey.kt
Note there's a suppressed deprecation or two, talked with @Egorand about them and I think we're going to reevaluate their deprecations since they're valid for java types
> Fix some misc deprecated KotlinPoet APIs

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/metadata.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
Resolves #1244
Added a test with intersection types as well. While KotlinPoet handles these backward referencing types, we need to handle it (using the same resolver mechanism) when transforming types in a deep copy.
> Fix infinite loop with type var variance stripping + remove from API

- build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- kotlin/codegen/build.gradle.kts
- kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DefaultConstructorTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/ComplexGenericsInheritanceTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/MultipleMasksTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
- moshi/build.gradle.kts
- moshi/gradle.properties
- moshi/src/main/java/com/squareup/moshi/-MoshiKotlinExtensions.kt
- moshi/src/main/java/com/squareup/moshi/-MoshiKotlinTypesExtensions.kt
- moshi/src/main/java/com/squareup/moshi/internal/Util.java
- moshi/src/test/java/com/squareup/moshi/CircularAdaptersTest.java
- moshi/src/test/java/com/squareup/moshi/KotlinExtensionsTest.kt
Continuation of #969, but with Kotlin 1.4 and formal availability of reflect-less `typeOf()`
* This adds extensions in a few places. We probably don't want all of them, but putting them here for consideration based on personal experience and ones I've found myself writing in multiple projects.
* Makes the `moshi` artifact a kotlin project but with the stdlib only as a `compileOnly` dependency. Only kotlin consumers would be able to use these APIs
* Fixed a couple of gradle/java version configuration I noticed along the way
* Some APIs seem inviting, like `Class<*>.parameterizedBy(...)`, but I avoided adding these because the whole point is that `typeOf()` allows us to avoid these.
> Promote Kotlin type-inferring APIs to the main Moshi package (round 2!)

- .github/workflows/build.yml
This PR reverts #1255 and fixes #1294 by switching back to using `pull_request` instead of `pull_request_target`. This will correctly run tests against the updated code in PRs, instead of against the base branch.
> Revert pull-request-target to pull-request

- adapters/build.gradle.kts
- adapters/japicmp/build.gradle.kts
- build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- examples/build.gradle.kts
- kotlin/codegen/build.gradle.kts
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/JsonClassCodegenProcessor.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/TypeRenderer.kt
- kotlin/reflect/src/main/java/com/squareup/moshi/KotlinJsonAdapter.kt
- kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt
- kotlin/tests/build.gradle.kts
- moshi/build.gradle.kts
- moshi/gradle.properties
- moshi/japicmp/build.gradle.kts
- moshi/src/main/java/com/squareup/moshi/-MoshiKotlinExtensions.kt
- moshi/src/main/java/com/squareup/moshi/-MoshiKotlinTypesExtensions.kt
- settings.gradle.kts
Completes part 1 of #1252 
* Adds japicmp for `moshi` and `adapters` projects
* Adds animalsniffer. We don't target Java 8 yet though like okio/okhttp, but keeping this as a toe-hold
* Prepares `moshi` and `adapters` as full kotlin projects
* Configure all kotlin projects with common `KotlinCompile` task configuration and explicit API mode
> Prepare project for Kotlin migration

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
KotlinPoet always generates explicit `PUBLIC` modifiers for public members now, so this avoid another point of compiler warnings in generated code
> Suppress RedundantVisibilityModifier in generated adapters

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
> Reserve simple type names referenced by properties to avoid collisions

- buildSrc/src/main/kotlin/Dependencies.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
This resolves #1272 by creating an array class with the raw type of the generic, which matches how kotlin treats cases like the one in the linked issue. See https://github.com/square/moshi/issues/1272#issuecomment-787703904
> Support generic arrays with defaults in code gen

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
Since we don't get parameter hints or the ability to do named parameters on these, this makes them a tad more readable when just using default values for unfulfilled parameters
> Improve readability of constructor invocation params

- kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt
This is my first time posting pull request and I am not good at English, so I'm sorry if there is something wrong with it.
If the arguments are fully specified (= don't have to use `Default arguments`), can speed up by making a invoke with `KFunction.call`.
Currently `KotlinJsonAdapter` does mapping by calling` KFunction.callBy`.
On the other hand, [`KFunction.callBy` has about 1/5 the performance of` KFunction.call`](https://github.com/ProjectMapK/FastKFunction#how-fast), so you can expect speedup by doing `KFunction.call` as much as possible.
I tried to achieve this by making `IndexedParameterMap` manage the initialization state.
Which `branch` is the appropriate destination for a `pull request`?
I'm expecting `moshi_1.11.x`, but I'm tentatively specifying `master`.
I'm thinking of …
> Improve KotlinJsonAdapter performance by invoke KFunction by "call".

- README.md
Fixed from `1.11.0` to `1.12.0`.
Still have 1.11.0 in the following part, should fix it?
https://github.com/square/moshi/blob/1654313feed48ab09e6edfe7ebbef23a57869020/moshi/japicmp/build.gradle.kts#L28
https://github.com/square/moshi/blob/1654313feed48ab09e6edfe7ebbef23a57869020/adapters/japicmp/build.gradle.kts#L28
I'm not good at English, so I'm sorry if there is any rudeness.
> Fix version on readme

- adapters/build.gradle.kts
- build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- kotlin/codegen/build.gradle.kts
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/DelegateKey.kt
- kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt
- kotlin/tests/build.gradle.kts
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/codegen/annotation/UppercaseInAnnotationPackage.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
- moshi/build.gradle.kts
This updates to Kotlin 1.5. Note that there's a larger KotlinPoet update in the works too, as there's a few changes in the kotlinx-metadata infrastructure.
This starts some preliminary support of value classes, but only just bumping our test example up.
Other bits:
* Auto-migrated some deprecated APIs
* Kept jvmTarget at "1.6" for backward compatibility, but we could revisit this
* ktlint update has to go with this too as newer version supports the `value class` keyword combo
> Update to Kotlin 1.5 (and associated deps)

- .github/workflows/build.yml
- adapters/build.gradle.kts
- build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- examples/src/main/java/com/squareup/moshi/recipes/FallbackEnum.java
- gradle.properties
- kotlin/codegen/build.gradle.kts
- kotlin/tests/build.gradle.kts
- moshi/build.gradle.kts
- moshi/records-tests/build.gradle.kts
- moshi/records-tests/src/test/java/com/squareup/moshi/RecordsTest.java
- moshi/records-tests/src/test/java/com/squareup/moshi/records/RecordsTest.java
- moshi/src/main/java/com/squareup/moshi/Moshi.java
- moshi/src/main/java/com/squareup/moshi/RecordJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/internal/Util.java
- moshi/src/main/java16/com/squareup/moshi/RecordJsonAdapter.java
- moshi/src/test/java/com/squareup/moshi/JsonAdapterTest.java
- moshi/src/test/java/com/squareup/moshi/JsonReaderTest.java
- moshi/src/test/java/com/squareup/moshi/JsonValueReaderTest.java
- moshi/src/test/java/com/squareup/moshi/JsonValueWriterTest.java
- moshi/src/test/java/com/squareup/moshi/JsonWriterTest.java
- settings.gradle.kts
Porting from https://github.com/ZacSweers/MoshiX/tree/main/moshi-records-reflect
This makes a few changes along the way to make the build all happy with how we're doing this:
- Standardizing around Java 8 (which is the minimum supported by gradle toolchains and also soon to be the minimum supported by Kotlin)
- Create a separate Java 16 source set for hosting the actual adapter implementation. This is compiled with Java 16 but is then packaged into the main Moshi jar and denoted as a Multi-Release JAR.
- We gate access to this record adapter at runtime by checking if the requisite record APIs are available.
- We separately have a shim copy of the record adapter in the `main` source set for linking in `BUILT_IN_FACTORIES`, but this is booted out by the real one during packaging.
- Replace …
> Implement reflective support for Java Records

- README.md
I've updated the README to include a section to describe how to work with enums in builds using Proguard/R8.
Cheers!
> Update README to include enum section in ProGuard/R8 rules

- kotlin/codegen/build.gradle.kts
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/DelegateKey.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/InternalMoshiCodegenApi.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/Options.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/ProguardRules.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/PropertyGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/TargetConstructor.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/TargetParameter.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/TargetProperty.kt
This is functionally no different than before, but allows for external use of these APIs for consumers that are willing to forgo support/API stability. This allows use of these processing-agnostic APIs in multiple contexts while reusing the same logic Moshi uses today for generating adapters.
> Switch from internal to experimental internal annotation

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/TargetTypes.kt
- kotlin/tests/codegen-only/src/test/kotlin/com/squareup/moshi/kotlin/codegen/CompileOnlyTests.kt
- kotlin/tests/extra-moshi-test-module/src/main/kotlin/com/squareup/moshi/kotlin/codegen/test/extra/AbstractClassInModuleA.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
For now it doesn't work due to https://github.com/google/ksp/issues/710, but it will eventually work once that's fixed. This puts in a check and a toe-hold comment in tests for it
> Support externally-compiled transient property recognition in KSP

- adapters/src/main/java/com/squareup/moshi/adapters/EnumJsonAdapter.java
- examples/src/main/java/com/squareup/moshi/recipes/FallbackEnum.java
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/TargetParameter.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/TargetProperty.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/apt/metadata.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/MoshiApiUtil.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/TargetTypes.kt
- kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/apt/JsonClassCodegenProcessorTest.kt
- kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/ksp/JsonClassSymbolProcessorTest.kt
- kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt
- kotlin/tests/extra-moshi-test-module/build.gradle.kts
- kotlin/tests/extra-moshi-test-module/src/main/kotlin/com/squareup/moshi/kotlin/codegen/test/extra/AbstractClassInModuleA.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/Json.java
- moshi/src/main/java/com/squareup/moshi/StandardJsonAdapters.java
- moshi/src/main/java16/com/squareup/moshi/RecordJsonAdapter.java
- moshi/src/test/java/com/squareup/moshi/ClassJsonAdapterTest.java
This introduces a new `ignore` property to the `@Json` annotation. It's semantically similar to `transient`, but without being JVM-specific or relying on backing fields.
```kotlin
class Example(...) {
@Json(ignore = true)
val someComputedProperty: String get() = "hi!"
}
```
This property defaults to `false` and also makes `Json.name` no longer required, instead opting for a "known default value" that we check against to see if it's been set before.
This resolves a number of outstanding issues around handling transience in Kotlin in particular!
* resolves #609
* resolves #1259
* resolves #1151
* Also helps with past issues like #1301, #1262, #1153
It is not supported in record classes or enums, which cannot reasonably support this. Enums could possibly support it, but I couldn't find an …
> Add `@Json.ignore` 

- .github/workflows/build.yml
- gradle/libs.versions.toml
- kotlin/codegen/build.gradle.kts
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/TargetTypes.kt
- kotlin/codegen/src/test/java/com/tschuchort/compiletesting/Ksp.kt
- kotlin/tests/extra-moshi-test-module/src/main/kotlin/com/squareup/moshi/kotlin/codegen/test/extra/AbstractClassInModuleA.kt
This allows us to fully support transient across compilation boundaries
> Update to KSP 1.0.1 and use new jvm modifiers resolver API

- .github/workflows/build.yml
- gradle.properties
- gradle/libs.versions.toml
- kotlin/codegen/build.gradle.kts
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/DelegateKey.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/ProguardRules.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/TargetType.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/apt/JsonClassCodegenProcessor.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/apt/metadata.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/JsonClassSymbolProcessorProvider.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/MoshiApiUtil.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/TargetTypes.kt
- kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/apt/JsonClassCodegenProcessorTest.kt
- kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/ksp/JsonClassSymbolProcessorTest.kt
This fully upgrades to Kotlin 1.6 and removes the controls for whether or not to instantiate annotations. Instead, this now just requires Kotlin 1.6 going forward.
> Upgrade to Kotlin 1.6 + always instantiate annotations

- moshi/src/main/resources/META-INF/proguard/moshi.pro
R8 3.1 in full mode have made improvements to annotation removal.
Current rules are not enough to ensure that JsonQualifier  annotatated class are kept.
See https://issuetracker.google.com/issues/206656057
Proper change attributed to: Morten Krogh-Jespersen
> Update proguard rules for R8 3.1

- gradle/libs.versions.toml
Buys us extra time to kotlin 1.7.0 too
https://github.com/JetBrains/kotlin/blob/master/libraries/kotlinx-metadata/jvm/ChangeLog.md#040
> Update kotlinx-metadata to 0.4.0

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/DelegateKey.kt
- moshi/src/main/java/com/squareup/moshi/Moshi.java
> Omit adapter field names now that we directly instantiate annotations

- moshi/src/main/java/com/squareup/moshi/Types.java
This was only used by generated kotlin code prior to direct annotation instantiation
> Deprecate Types.getFieldJsonQualifierAnnotations

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/DelegateKey.kt
- moshi/src/main/java/com/squareup/moshi/Moshi.java
> Revert "Omit adapter field names now that we directly instantiate annotations"

- kotlin/tests/codegen-only/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
- moshi/src/main/java/com/squareup/moshi/Moshi.java
Some of the cleanups in #1380 were actually breaking intentional code
> Fix code cleanups

- moshi/records-tests/src/test/java/com/squareup/moshi/records/RecordsTest.java
- moshi/src/main/java16/com/squareup/moshi/RecordJsonAdapter.java
Without the fix the test fails like so:
No JsonAdapter for T (with no annotations)
for T
for java.util.List<T>
for com.squareup.moshi.records.RecordsTest$IndirectGenerics<java.lang.Long>
for class com.squareup.moshi.records.RecordsTest$HasIndirectGenerics
java.lang.IllegalArgumentException: No JsonAdapter for T (with no annotations)
for T
for java.util.List<T>
for com.squareup.moshi.records.RecordsTest$IndirectGenerics<java.lang.Long>
for class com.squareup.moshi.records.RecordsTest$HasIndirectGenerics
at com.squareup.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:389)
at com.squareup.moshi.Moshi.adapter(Moshi.java:158)
at com.squareup.moshi.Moshi.adapter(Moshi.java:106)
at com.squareup.moshi.Moshi.adapter(Moshi.java:75)
> Fix a crash when combining generics and records

- moshi/records-tests/src/test/java/com/squareup/moshi/records/RecordsTest.java
- moshi/src/main/java16/com/squareup/moshi/RecordJsonAdapter.java
Without this we get an AssertionError, which is the wrong exception
type for a JSON schema mismatch:
java.lang.AssertionError: java.lang.NullPointerException: Cannot invoke "java.lang.Number.intValue()" because the return value of "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, Object, boolean)" is null
at com.squareup.moshi.RecordJsonAdapter.fromJson(RecordJsonAdapter.java:168)
at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
at com.squareup.moshi.records.RecordsTest.absentPrimitiveFails(RecordsTest.java:257)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Number.intValue()" because the return value of …
> Fail gracefully when a primitive value is absent.

- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/apt/metadata.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/TargetTypes.kt
- kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
Without this fix the new test fails like this:
value of: toJson(...)
expected: {"$a":"apple","$b":"banana"}
but was : {"${'$'}a":"apple","$b":"banana"}
> Don't mangle property names that contain a dollar sign

- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.java
- moshi/src/main/java/com/squareup/moshi/JsonReader.java
- moshi/src/main/java/com/squareup/moshi/JsonWriter.java
Whoever thought this was a good idea is wrong.
> Task :moshi:javadoc
/home/runner/work/moshi/moshi/moshi/src/main/java/com/squareup/moshi/JsonWriter.java:40: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
* <h3>Encoding JSON</h3>
^
/home/runner/work/moshi/moshi/moshi/src/main/java/com/squareup/moshi/JsonReader.java:40: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
* <h3>Parsing JSON</h3>
^
> Submit to Javadoc's draconion heading ordering rule

- moshi/src/main/java/com/squareup/moshi/JsonReader.java
- moshi/src/main/java/com/squareup/moshi/JsonWriter.java
The javadoc task assumes every doc starts with h1 and thus using them anywhere in the body after the start is an error ¯\_(ツ)_/¯. This just changes them to h2
> Fix javadoc task and snapshots

- README.md
`val` is readonly in Kotlin. They can be assigned a value only once. The example was showing error when I tried to use it.
> EventJsonAdapter Kotlin sample update in README file

- moshi-kotlin-tests/codegen-only/src/test/kotlin/com/squareup/moshi/kotlin/codegen/ComplexGenericsInheritanceTest.kt
- moshi-kotlin-tests/codegen-only/src/test/kotlin/com/squareup/moshi/kotlin/codegen/DefaultConstructorTest.kt
- moshi-kotlin-tests/codegen-only/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
- moshi-kotlin-tests/codegen-only/src/test/kotlin/com/squareup/moshi/kotlin/codegen/MixingReflectAndCodeGen.kt
- moshi-kotlin-tests/codegen-only/src/test/kotlin/com/squareup/moshi/kotlin/codegen/MoshiKspTest.kt
- moshi-kotlin-tests/codegen-only/src/test/kotlin/com/squareup/moshi/kotlin/codegen/MultipleMasksTest.kt
- moshi-kotlin-tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
- moshi-kotlin-tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
- moshi/src/main/java/com/squareup/moshi/-MoshiKotlinExtensions.kt
- moshi/src/main/java/com/squareup/moshi/Moshi.kt
No need to be separate anymore and saves us an import. Still binary-compatible with before!
> Inline Moshi extension functions to Moshi itself

- gradle/libs.versions.toml
`Dokka` is a documentation engine for Kotlin. So, it make sense to keep the same version as Kotlin.
https://github.com/Kotlin/dokka/releases
> Update dokka to 1.6.10

- moshi/src/main/resources/META-INF/proguard/moshi.pro
These are looked up reflectively and must be preserved
> Keep `@FromJson`/`@ToJson`-annotated methods in proguard

- moshi/src/main/java/com/squareup/moshi/AdapterMethodsFactory.kt
- moshi/src/main/java/com/squareup/moshi/ClassJsonAdapter.kt
- moshi/src/main/java/com/squareup/moshi/Moshi.kt
- moshi/src/main/java/com/squareup/moshi/Types.kt
See individual commits! Just tidying some things up
> Small cleanups from a few past PRs

- moshi/japicmp/build.gradle.kts
- moshi/src/main/java/com/squareup/moshi/internal/Util.kt
This is used occasionally from generated code so we have to be explicit about what members of `Util` are part of the effective public API. This exposed a missing `@JvmField` along the way.
> Explicitly denote util public APIs in japicmp

- README.md
Someone in kotlin lang interpreted this to mean it only worked with the specific version mentioned
> Comment about KSP version

- moshi-kotlin-codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
We are getting this warning on generated type adapters with Kotlin `1.6.21` and moshi `1.14.0-SNAPSHOT` published from [this commit](https://github.com/square/moshi/commit/53bb46c20839fe155cdfcc042553d4acf6237344) :
`Parameter 'moshi' is never used`
`"unused"` doesn't seem to suppress that, but `"UNUSED_PARAMETER"` does work.
I couldn't figure out how to get `kotlin-compile-testing` to output the warning, so I could write a test to assert the warning is gone.
> Suppress warning in generated code: `Parameter 'moshi' is never used`

- .github/workflows/build.yml
> [CI] Bump JDK from `18` to `19`

- moshi-kotlin-codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/JsonClassSymbolProcessorProvider.kt
- moshi-kotlin-codegen/src/test/java/com/squareup/moshi/kotlin/codegen/ksp/JsonClassSymbolProcessorTest.kt
Follow up to the error/stack I posted in #1522 
After poking around on my project I realized I had some bad generics syntax in my test source set causing the intrinsic null check failure in the ksp task.
Messaging now at least provides a hint as to where to start investigating
> KSP error messaging: Include name of the type being processed when creating the adapterGenerator fails

- gradle/libs.versions.toml
- kotlin/codegen/build.gradle.kts
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/apt/JsonClassCodegenProcessor.kt
- kotlin/codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/JsonClassSymbolProcessorProvider.kt
- kotlin/codegen/src/test/java/com/squareup/moshi/kotlin/codegen/ksp/JsonClassSymbolProcessorTest.kt
- moshi/build.gradle.kts
- Upgrade to Kotlin `1.8.21`
- Upgrade to KSP `1.8.21-1.0.11`
- Upgrade to kotlinx-metadata `0.6.0`
- Upgrade to KotlinPoet `1.13.2`
- Support Kotlin language version `1.9.0` in Kapt
- Backport 076ee610759c077b7e84d2ba3ac603017a5c26e4
- Backport 000ce304187a6f655f5359ad14df5b5981916607
- Deprecate kapt code gen support w/ a noisy warning message in its processor init
> 1.15.0 preperations

- README.md
By default, open Kotlin code examples instead of Java.
> Open Kotlin sampels by default in README.md

- moshi-kotlin-codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/AdapterGenerator.kt
- moshi-kotlin-codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/kotlintypes.kt
Hi, Square folks.
The background here is that we're working to put nullness annotations on
more "JDK classes," such as `java.lang.Class`, at least in Google's
build system. That means that calls to methods like
`clazz.getMethod(...)` and `clazz.getDeclaredConstructor` must pass
non-nullable `Class` instances. If they don't, we see errors:
```
error: type mismatch: inferred type is Class<Int>? but Class<*> was expected
String::class.java, String::class.java, Int::class.javaPrimitiveType, String::class.java,
^
```
```
error: type mismatch: inferred type is Class<Int>? but Class<*> was expected
String::class.java, FooResponse::class.java, Int::class.javaPrimitiveType,
^
```
```
error: type mismatch: inferred type is Class<CapturedType(*)>? but Class<*> was expected …
```
> Insert `!!` to make some types in generated code non-nullable.

- build.gradle.kts
- gradle/libs.versions.toml
- moshi-adapters/japicmp/build.gradle.kts
- moshi-adapters/src/main/java/com/squareup/moshi/adapters/Iso8601Utils.kt
- moshi-kotlin-codegen/build.gradle.kts
- moshi-kotlin-tests/build.gradle.kts
- moshi-kotlin-tests/codegen-only/build.gradle.kts
- moshi-kotlin-tests/codegen-only/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
- moshi-kotlin-tests/codegen-only/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest_CustomGeneratedClassJsonAdapter.kt
- moshi-kotlin-tests/src/test/kotlin/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterTest.kt
- moshi-kotlin/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapterFactory.kt
- moshi/build.gradle.kts
- moshi/japicmp/build.gradle.kts
- moshi/src/main/java/com/squareup/moshi/JsonUtf8Reader.kt
- moshi/src/main/java/com/squareup/moshi/JsonWriter.kt
Ensure renovate can bump them by specifying full coordinates in toml.
> Update formatters to latest

- README.md
Mostly due to [CVE-2023-3635](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-3635)
> Update README.md dependency version 1.15.0 to 1.15.1

- moshi-adapters/src/main/java/com/squareup/moshi/adapters/Iso8601Utils.kt
- moshi-adapters/src/main/java/com/squareup/moshi/adapters/Rfc3339DateJsonAdapter.kt
`Rfc3339DateJsonAdapter` can convert a nullable `Date` object to a JSON string and vice versa.
If a system attempts to concurrently serialize or deserialize large objects containing many `Date` objects or collections of those large objects, there could be contention across threads and delays due to synchronization.
`fromJson` constructs and uses a local `Calendar` instance and does not use any shared `DateFormat`, thus it should not need to be synchronized.
`toJson` calls `Date.formatIsoDate` extension method, which provides a (mutable) `Date` object to local `Calendar` instance.
```kotlin
internal fun Date.formatIsoDate(): String {
val calendar: Calendar = GregorianCalendar(TIMEZONE_Z, Locale.US)
calendar.time = this
// ...
}
```
The underlying code for `calendar.time = this` simply gets …
> Remove @Synchronized annotation from `Rfc3339DateJsonAdapter`.

- .github/workflows/build.yml
- .github/workflows/gradle-wrapper.yml
- build.gradle.kts
- gradle/libs.versions.toml
- moshi/build.gradle.kts
- Gradle caching on CI
- JDK 21
- Move gradle wrapper validation to a separate workflow that only runs on changes to those files
> Update CI/build infra

- moshi-kotlin-codegen/src/main/java/com/squareup/moshi/kotlin/codegen/api/ProguardRules.kt
- moshi-kotlin-codegen/src/test/java/com/squareup/moshi/kotlin/codegen/ksp/JsonClassSymbolProcessorTest.kt
Fixes #1911.
@christofferqa (who works on R8 at Google) was looking into Monzo's slow R8 builds. One thing he found was removing redundant `-if` rules generated by Moshi reduced the time we spend in R8 by about 8% (we have ~2.8k classes  annotated with `@JsonClass`).
> Remove redundant preconditions from generated ProGuard rules

- build.gradle.kts
Replaces the deprecated `indentWithSpace` with `leadingTabsToSpace` as discussed in [spotless#794](https://github.com/diffplug/spotless/issues/794).
Since `leadingTabsToSpace` has been available since spotless Gradle plugin `7.0.0`, and moshi currently uses `7.0.3`, it's safe to adopt the new API.
> Replace deprecated `indentWithSpaces` with `leadingTabsToSpaces`

- .github/workflows/build.yml
- CHANGELOG.md
- README.md
- build.gradle.kts
See (internally) http://go/central-portal-migration-com-squareup for context.
> Migrate to Sonatype Central Portal

- moshi-kotlin-codegen/src/main/java/com/squareup/moshi/kotlin/codegen/ksp/KspUtil.kt
- moshi-kotlin-tests/codegen-only/src/test/kotlin/com/squareup/moshi/kotlin/codegen/GeneratedAdaptersTest.kt
- moshi-kotlin-tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt
Fix for https://github.com/square/moshi/issues/1995
If you have an annotation applied to your  POJOs and that annotation has a default parameter in its list, the new adapter generator would fail to produce a fully qualified name for the type.
This is my best-attempt, I'm not familiar with all the intricacies of resolving the type information here.
I'd be glad to improve on this if someone points me in the right direction.
> Work-around for missing fqn on default args to annotations
